### PR TITLE
Add erlang package.

### PR DESCRIPTION
**Pull request by dlorenc**
This is required for rabbitmq.

Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>

### CODE REVIEW

**Comment by tuananh** [comment]
I was doing the same thing last night, working on elixir and erlang pkg :))

**Comment by dlorenc** [comment]
> I was doing the same thing last night, working on elixir and erlang pkg :))

How did I do?? I can dro

**Comment by tuananh** [comment]
Oh no. Please keep it open. I havent finished mine yet

**Comment by dlorenc** [comment]
Ok! Feel free to push changes to mine.

**Review by kaniini — APPROVED** [review]

**Review by rawlingsj — APPROVED** [review]

**Pull request merged**
