### PR TITLE
Revert "only run GHA presubmit if 'github-build' label is applied"

### PR DESCRIPTION
**Pull request by ajayk**
Reverts wolfi-dev/os#29581

bincapz fails without artifacts from github action workflow

### CODE REVIEW

**Review by k4leung4 — APPROVED** [review]
can you update the description to what went wrong
possibly a link to a failed instance? or error msg?

**Comment by xnox** [comment]
> can you update the description to what went wrong possibly a link to a failed instance? or error msg?

lack of the bot comment like in this pr; and a label that bincapz/passed. See for example https://github.com/wolfi-dev/os/pull/29594

**Comment by xnox** [comment]
Monitoring https://github.com/wolfi-dev/os/pull/29597 to work correctly

**Comment by xnox** [comment]
bincapz passed on https://github.com/wolfi-dev/os/pull/29597

**Pull request merged**
