### PR TITLE
feat: Makefile target for running interactive Wolfi

### PR DESCRIPTION
**Pull request by stormqueen1990**
Add a Makefile target to run an interactive Wolfi container for package testing purposes.

### CODE REVIEW

**Comment by vaikas** [comment]
When I try this on my setup, I get this:
```
vaikas@vaikas-MBP os % make local-wolfi
docker run --rm -it \
		--mount type=bind,source="/Users/vaikas/projects/go/src/github.com/wolfi-dev/os/packages",destination="/work/packages",readonly \
		--mount type=bind,source="/Users/vaikas/projects/go/src/github.com/wolfi-dev/os/local-melange.rsa.pub",destination="/etc/apk/keys/local-melange.rsa.pub",readonly \
		--mount type=bind,source="/var/folders/58/jvmk7c016fx9p6j1717qcv3c0000gn/T/tmp.FDZHEj04/repositories",destination="/etc/apk/repositories",readonly \
		-w "/work/packages" \
		cgr.dev/chainguard/wolfi-base:latest
e90d9a8f2909:/work/packages# apt
/bin/sh: apt: not found
```

**Comment by stormqueen1990** [comment]
> When I try this on my setup, I get this:
> 
> ```
> e90d9a8f2909:/work/packages# apt
> /bin/sh: apt: not found
> ```

Is `apt` what you're looking for? Shouldn't it be `apk` instead?

**Comment by vaikas** [comment]
LOL, I'm so sorry for the confusion!!! Old habits die hard :)

**Review by vaikas — DISMISSED** [review]
Works like magic!!! Strong work!!!

**Review by rawlingsj — DISMISSED** [review]

**Review by rawlingsj — APPROVED** [review]

**Review by kaniini — APPROVED** [review]

**Pull request merged**
