### PR TITLE
Sprinkle more `strip` around Go builds

### PR DESCRIPTION
**Pull request by mattmoor**
continuation of: https://github.com/wolfi-dev/os/pull/6477

### CODE REVIEW

**Review by imjasonh — DISMISSED** [review]

**Comment by mattmoor** [comment]
Looks like gatekeeper may have updated a tag, will investigate 🤔

**Comment by mattmoor** [comment]
It looks like they JUST updated this an hour ago: 
image

We picked it up 4 days ago: https://github.com/wolfi-dev/os/commit/5ebd910efbc80048a98e55d811758503332c3036

**Comment by mattmoor** [comment]
I rebased this and added a commit to reflect the gatekeeper tag update here: https://github.com/open-policy-agent/gatekeeper/issues/3044

**Comment by mattmoor** [comment]
Ok I incorporated another fix for `ingress-nginx-controller` where the `--depth=1` -> `checkout ${commit}` broke due to an upstream commit: https://github.com/google/ngx_brotli/pull/157

**Review by ajayk — APPROVED** [review]

**Pull request merged**
