### PR TITLE
Add a deno package!

### PR DESCRIPTION
**Pull request by dlorenc**
There's one patch in here to override some faulty detection in their build.rs script. The script was trying to detect what version of glibc we use with ldd. We don't package ldd, and even when I tried pretending we do their string matching was pretty funky and not terribly robust.

### CODE REVIEW

**Comment by tuananh** [comment]
@dlorenc you're on fire lately :fire: :+1:

**Review by luhring — DISMISSED** [review]
>We don't package ldd

I think we do have `ldd` (in `posix-libc-utils`), but I'm still good with removing this detection if it's causing problems

**Comment by dlorenc** [comment]
> > We don't package ldd
> 
> I think we do have `ldd` (in `posix-libc-utils`), but I'm still good with removing this detection if it's causing problems

Hmm...

```shell
% docker run -it cgr.dev/chainguard/wolfi-base
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2a5d8248ffeb:/# posix-libc-utils
/bin/sh: posix-libc-utils: not found
2a5d8248ffeb:/# apk add posix-libc-utils
fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
(1/1) Installing posix-libc-utils (2.36-r3)
Executing busybox-1.35.0-r4.trigger
OK: 12 MiB in 12 packages
2a5d8248ffeb:/# ldd
/bin/sh: ldd: not found
```

**Comment by tuananh** [comment]
> > > We don't package ldd
> > 
> > 
> > I think we do have `ldd` (in `posix-libc-utils`), but I'm still good with removing this detection if it's causing problems
> 
> Hmm...
> 
> ```shell
> % docker run -it cgr.dev/chainguard/wolfi-base
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> 2a5d8248ffeb:/# posix-libc-utils
> /bin/sh: posix-libc-utils: not found
> 2a5d8248ffeb:/# apk add posix-libc-utils
> fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
> (1/1) Installing posix-libc-utils (2.36-r3)
> Executing busybox-1.35.0-r4.trigger
> OK: 12 MiB in 12 packages
> 2a5d8248ffeb:/# ldd
> /bin/sh: ldd: not found
> ```

ldd is in there. however, ldd is just a bash script so i think we need to add bash as runtime dependency there.

you can try by install posix-libc-utils and bash and then run ldd

**Comment by dlorenc** [comment]
> > > > We don't package ldd
> > > 
> > > 
> > > I think we do have `ldd` (in `posix-libc-utils`), but I'm still good with removing this detection if it's causing problems
> > 
> > 
> > Hmm...
> > ```shell
> > % docker run -it cgr.dev/chainguard/wolfi-base
> > WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> > 2a5d8248ffeb:/# posix-libc-utils
> > /bin/sh: posix-libc-utils: not found
> > 2a5d8248ffeb:/# apk add posix-libc-utils
> > fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
> > (1/1) Installing posix-libc-utils (2.36-r3)
> > Executing busybox-1.35.0-r4.trigger
> > OK: 12 MiB in 12 packages
> > 2a5d8248ffeb:/# ldd
> > /bin/sh: ldd: not found
> > ```
> 
> ldd is in there. however, ldd is just a bash script so i think we need to add bash as runtime dependency there.
> 
> you can try by install posix-libc-utils and bash and then run ldd

All fixed now! Yay!

**Review by luhring — APPROVED** [review]

**Review by rawlingsj — APPROVED** [review]

**Pull request merged**
