### PR TITLE
Add php-common subpackage to php-8.1

### PR DESCRIPTION
**Pull request by vaikas**
Used the following to figure out how it may / should look like:
https://git.alpinelinux.org/aports/plain/community/php81/APKBUILD

And also, checked what the expected package outputs:
https://pkgs.alpinelinux.org/contents?branch=edge&name=php81%2dcommon&arch=aarch64&repo=community

Tested with `make local-wolfi`
```
40364132da67:/work/packages# apk add php-8.1
(1/7) Installing xz (5.4.4-r0)
(2/7) Installing libxml2 (2.11.5-r0)
(3/7) Installing ncurses-terminfo-base (6.4_p20230722-r1)
(4/7) Installing ncurses (6.4_p20230722-r1)
(5/7) Installing readline (8.2-r2)
(6/7) Installing sqlite (3.40.0-r1)
(7/7) Installing php-8.1 (8.1.23-r0)
OK: 31 MiB in 21 packages
40364132da67:/work/packages# apk add php-common
(1/1) Installing php-common (8.1.23-r0)
OK: 31 MiB in 22 packages
40364132da67:/work/packages# apk info -L php-common
php-common-8.1.23-r0 contains:
etc/php/php.ini
var/lib/db/sbom/php-common-8.1.23-r0.spdx.json
40364132da67:/work/packages# ls -l /etc/php/php.ini
-rw-r--r--    1 root     root         73603 Sep  6 22:46 /etc/php/php.ini
```

You can also install it individually with `apk add php-8.1`

#### For new package PRs only
- [ X ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ X ] REQUIRED - The version of the package is still receiving security updates

### CODE REVIEW

**Comment by vaikas** [comment]
Looks like there was a flake in the CI build action:
```
Checking docker version
  /usr/bin/docker version --format '{{.Server.APIVersion}}'
  Cannot connect to the Docker daemon at tcp://localhost:[2](https://github.com/wolfi-dev/os/actions/runs/6103250003/job/16563346437?pr=5217#step:2:2)[3](https://github.com/wolfi-dev/os/actions/runs/6103250003/job/16563346437?pr=5217#step:2:3)76. Is the docker daemon running?
  '
  Error: Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'version --format '{{.Server.APIVersion}}''.
```

**Comment by joshrwolf** [comment]
> Looks like there was a flake in the CI build action:
> 
> ```
> Checking docker version
>   /usr/bin/docker version --format '{{.Server.APIVersion}}'
>   Cannot connect to the Docker daemon at tcp://localhost:[2](https://github.com/wolfi-dev/os/actions/runs/6103250003/job/16563346437?pr=5217#step:2:2)[3](https://github.com/wolfi-dev/os/actions/runs/6103250003/job/16563346437?pr=5217#step:2:3)76. Is the docker daemon running?
>   '
>   Error: Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'version --format '{{.Server.APIVersion}}''.
> ```

thanks for flagging this! I'm working on it 😅

**Comment by vaikas** [comment]
After rename tested with:
```
fc0292793d47:/work/packages# apk add php-8.1-config
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/1) Installing php-8.1-config (8.1.23-r1)
OK: 11 MiB in 15 packages
fc0292793d47:/work/packages# apk info -L php-8.1-config
php-8.1-config-8.1.23-r1 contains:
etc/php/php.ini
var/lib/db/sbom/php-8.1-config-8.1.23-r1.spdx.json
```

**Comment by kaniini** [comment]
I don't think we actually need to merge this.  It is for backwards compatibility with some Alpine PHP packages, but these packages have never been in Wolfi.

**Pull request closed without merging**
