### PR TITLE
Add ImageMagick.

### PR DESCRIPTION
**Pull request by amouat**
This is in progress and still needs subpackages split out. We're also missing some libraries so some formats are not currently supported.

Will add update data shortly...

Fixes:
https://github.com/wolfi-dev/os/issues/6063
Related:
https://github.com/wolfi-dev/os/pull/6064

#### For new package PRs only

- [ x ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ x ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
It's a variant of Apache
- [ x ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

### CODE REVIEW

**Comment by amouat** [comment]
Oh and the fetch is wrong. On it...

**Review by cpanato — COMMENTED** [review]
it lgtm

are we going to fix the cves before merging? or are you okay with that?

**Comment by amouat** [comment]
@cpanato I don't know how we can do that? I think we have to merge then issue advisories, right?

This is the newest version of the package, it should contain all fixes.

**Comment by cpanato** [comment]
@amouat, but maybe those cves are new and are not in the latest release :/

This is a new package, so I think we don't need to add advisories, only if we merge as is and fix it later

cc @luhring to correct me if i am wrong

**Comment by amouat** [comment]
Not sure I follow, maybe we should have a call?

I think the issue is the ImageMagick CVE data doesn't specify versions, so it applies to all versions unless an advisory is issued.

**Review by rawlingsj — APPROVED** [review]
Approving as advisories will follow.

**Comment by luhring** [comment]
>This is a new package, so I think we don't need to add advisories, only if we merge as is and fix it later
>
>cc @luhring to correct me if i am wrong

It's only "fixed" advisories that don't get added when a package is first introduced. Other advisories can and should be used as needed for new packages

**Pull request merged**
