### PR TITLE
build: remove non-existent noexecheap ld flag

### LINKED ISSUE #7419: Certain binaries struggle with our `-z,noexecheap` LDFLAG
Our grafana package for example errors with this, using our standard [`LDFLAGS`](https://github.com/wolfi-dev/os/blob/main/build-aarch64.env):

```shell
ℹ️  aarch64   | go build -ldflags -w -X main.version=10.2.0 -X main.commit=ae830f6 -X main.buildstamp=1698282480 -X main.buildBranch=HEAD -extldflags "-Wl,--as-needed,-O1,--sort-common -Wl,-z,relro,-z,now,-z,noexecstack,-z,noexecheap" -o ./bin/linux-arm64/grafana ./pkg/cmd/grafana
⚠️  aarch64   | # github.com/grafana/grafana/pkg/cmd/grafana
⚠️  aarch64   | /usr/lib/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
⚠️  aarch64   | /usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: warning: -z noexecheap ignored
⚠️  aarch64   | /usr/lib/gcc/aarch64-unknown-linux-gnu/13.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: read-only segment has dynamic relocations
⚠️  aarch64   | collect2: error: ld returned 1 exit status
```

A few other packages fail, and have the same workaround:

* https://github.com/wolfi-dev/os/blob/main/gst-plugins-base.yaml#L48
* https://github.com/wolfi-dev/os/blob/main/ruby-3.0.yaml#L47
* https://github.com/wolfi-dev/os/blob/main/wayland.yaml

### PR DESCRIPTION
**Pull request by xnox**
The LD flag -noexecheap was a gentoo/pax forked bintuils flag supported in versions 2.15..2.25. In addition to forked toolchain it also required forked/patched kernel. This option has been dropped from Hardened Gentoo binutils in approximately 2016. Yet many guides and tutorials online recommend setting it, when it is ignored by GNU LD and generates stderr warning only.

2024/03/11 12:46:58 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: -z noexecheap ignored

Same behaviour is observed on modern Gentoo as well. Clearly many packages do ensure that calls to ld are warning-free. Thus stop specifying this flag to unbreak building packages that are strict about it.

Fixes: https://github.com/wolfi-dev/os/issues/7419

Testing:
* Rebuilt all affected packages, they all build cleanly now.

### CODE REVIEW

**Comment by dlorenc** [comment]
Did you intentionally skip the epoch bump? Might be worth adding but I could be convinced either way.

**Comment by xnox** [comment]
> Did you intentionally skip the epoch bump? Might be worth adding but I could be convinced either way.

The rebuild of these packages will be a no-op, and thus produce no value to end users of either packages or images.
On the other hand, if we do want to force the builds of these no effective change rebuilds, to ensure this doesn't stand out, I can do epoch bump on these. I was erring on the side of not needing to ship updates of these.

Note github actions CI passed, and did rebuild all of these packages successfully.

**Comment by smoser** [comment]
I believe that semgrep error from #13781 ([log](https://github.com/wolfi-dev/os/actions/runs/8055488401/job/22002493877)) might be fixed by this, or at least smells that way. Log ended with:

> 2024/02/26 21:10:42 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: -z noexecheap ignored
> 2024/02/26 21:10:42 WARN Warning: 2 states have shift/reduce conflicts.
> 2024/02/26 21:10:42 WARN Warning: 2 shift/reduce conflicts were arbitrarily resolved.
> 2024/02/26 21:10:42 WARN Warning: 48 end-of-stream conflicts were arbitrarily resolved.
> 2024/02/26 21:10:42 WARN Warning: one state has shift/reduce conflicts.
> 2024/02/26 21:10:42 WARN Warning: one shift/reduce conflict was arbitrarily resolved.
> 2024/02/26 21:10:52 WARN File "src/main/dune", line 2, characters 8-12:
> 2024/02/26 21:10:52 WARN 2 |  (names Main)
> 2024/02/26 21:10:52 WARN             ^^^^
> 2024/02/26 21:10:52 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: -z noexecheap ignored
> 2024/02/26 21:10:52 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lz: No such file or directory
> 2024/02/26 21:10:52 WARN collect2: error: ld returned 1 exit status
> 2024/02/26 21:10:52 WARN File "caml_startup", line 1:
> 2024/02/26 21:10:52 WARN Error: Error during linking (exit code 1)
> 2024/02/26 21:10:52 INFO make[1]: Leaving directory '/home/build'
> 2024/02/26 21:10:52 WARN make[1]: *** [Makefile:122: minimal-build] Error 1
> 2024/02/26 21:10:52 WARN make: *** [Makefile:94: core] Error

**Comment by smoser** [comment]
> On the other hand, if we do want to force the builds of these no effective change rebuilds, to ensure this doesn't stand out, I can do epoch bump on these. I was erring on the side of not needing to ship updates of these.

My feeling here is that (outside of build-time and storage), the updates are just numbers and I'd rather build than not.  But I would defer to someone with more "this is what we typically would do in wolfi" experience than myself.

**Comment by xnox** [comment]
> I believe that semgrep error from #13781 ([log](https://github.com/wolfi-dev/os/actions/runs/8055488401/job/22002493877)) might be fixed by this, or at least smells that way. Log ended with:

it would fix the red-herring only (note the `... ignored` w.r..t. noexecheap) it is instead failing to find statically linked zlib, which when added explodes with other issues. As new upstream release has added dependency on curl, which is not quite possible to statically link, and yet support dlopen for the curl backend. Will propose a solution for that separately.

**Review by smoser — APPROVED** [review]

**Pull request merged**
