### PR TITLE
icu/73.1 manually update as melange bump doesnt work with var-transfo…

### LINKED ISSUE #1259: icu/73-1 new package update

### PR DESCRIPTION
**Pull request by rawlingsj**
…rms yet

fixes #1259

### CODE REVIEW

**Comment by rawlingsj** [comment]
CI soname check failure:
```
soname files differ, this can cause an ABI break.  

Existing soname files 
libicudata.so.71.1,libicui18n.so.71.1,libicuio.so.71.1,libicutest.so.71.1,libicutu.so.71.1,libicuuc.so.71.1
New soname files 
libicudata.so.73.1,libicui18n.so.73.1,libicuio.so.73.1,libicutest.so.73.1,libicutu.so.73.1,libicuuc.so.73.1

soname version check failed, libicudata has an existing version 71.1.0 while new package contains a different version 73.1.0.  This can cause ABI failures
```

**Comment by kaniini** [comment]
We will need to rebuild all the ICU dependents then when we merge this.  Thanks to the way Wolfi works, the old ICU won't get deleted, but still :)

**Comment by rawlingsj** [comment]
I've bumped the epoch for dependent packages in a following commit in this PR to be sure.

**Comment by rawlingsj** [comment]
`Wolfictl Check Updates` is expected to fail as melange bump doesn't work with var-transforms yet

**Comment by rawlingsj** [comment]
CI failure:
```
EXEC : error : RPC failed; curl 18 Recv failure: Connection reset by peer [/home/build/installer/src/SourceBuild/tarball/BuildSourceBuildTarball.proj]
```
going to retry

**Comment by rawlingsj** [comment]
wolfictl update check expected to fail as melange bump doesn't work with var transforms yet

**Comment by rawlingsj** [comment]
CI failure was related to the new soname version
```
soname version check failed, libicudata has an existing version 71.1.0 while new package contains a different version 73.1.0.
```
But as I've bumped all the dependent packages epoch to ensure they work I think this is ok?  

@kaniini WDYT?

**Pull request merged**
