### PR TITLE
rust: bump to 1.67.1

### PR DESCRIPTION
**Pull request by imjasonh**
Signed-off-by: Jason Hall <jason@chainguard.dev>

### CODE REVIEW

**Review by jdolitsky — DISMISSED** [review]

**Comment by rawlingsj** [comment]
Is this one of those packages where we also need to bump the epoch for packages that use rust to build themselves?

**Comment by kaniini** [comment]
Yeah we will have to, since Rust programs are basically staticly linked when it comes to crates.

**Comment by imjasonh** [comment]
Which packages will I need to bump?

Is there a way to encode this in the config itself so that we can sprinkle some sweet sweet automation on this?

**Comment by imjasonh** [comment]
CI fails with:

```
2023/02/17 20:20:22 melange (deno/x86_64):   Downloaded rustversion v1.0.11
2023/02/17 20:20:22 melange (deno/x86_64): error: failed to verify the checksum of `rustversion v1.0.11`
2023/02/17 20:20:22 ERROR: failed to build package. the build environment has been preserved:
```

This also recently happened in https://github.com/wolfi-dev/os/pull/540#issuecomment-1435164169

Is crates.io serving different stuff than expected?

**Comment by imjasonh** [comment]
Re-ran it, this time a different package:

```
melange (deno/x86_64): error: failed to verify the checksum of `derive_more v0.99.17`
```

(https://github.com/wolfi-dev/os/actions/runs/4206864193/jobs/7314511109#step:8:9767)

This package previously downloaded just fine (I think) from [the first attempt](https://github.com/wolfi-dev/os/actions/runs/4206864193/jobs/7300903377#step:8:10332).

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
