### PR TITLE
pull build deps from apk.cgr.dev/chainguard

### PR DESCRIPTION
**Pull request by imjasonh**

### CODE REVIEW

**Review by k4leung4 — APPROVED** [review]

**Comment by mattmoor** [comment]
Have we done a world build with this to ensure we aren't missing any APKs?

**Review by xnox — CHANGES_REQUESTED** [review]
```console
$ apkrane ls https://apk.cgr.dev/chainguard/x86_64/APKINDEX.tar.gz | sort > x86.list
$ ls *.yaml | xargs -I{} sh -c 'melange query {} "{{.Package.Name}}-{{.Package.Version}}-r{{.Package.Epoch}}.apk"; echo' >> melange.list
$ cat melange.list | sort | sponge melange.list
$ comm -13 x86.list melange.list | wc -l
201
$ apkrane ls https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz | sort > old-url.x86.list
$ comm -13 old-url.x86.list melange.list | wc -l
0
```

Either i am doing something wrong, or 201 .yaml files are missing. 

Should I commit them to `backfill-packages.txt` ?

**Comment by imjasonh** [comment]
I just backfilled a bunch of packages in https://github.com/wolfi-dev/os/pull/32100

If there are more that are missing we should backfill them.

**Comment by xnox** [comment]
> I just backfilled a bunch of packages in #32100
> 
> If there are more that are missing we should backfill them.

ok! i will wait for https://github.com/wolfi-dev/os/actions/runs/11557396223 to complete and then will re-run the check.

**Comment by imjasonh** [comment]
The backfill is complete, let me know if I missed anything.

**Comment by xnox** [comment]
> The backfill is complete, let me know if I missed anything.

```
$ comm -13 x86.list melange.list
unixodbc-2.3.12-r0.apk
```

Is missing.

**Comment by imjasonh** [comment]
> ```
> unixodbc-2.3.12-r0.apk
> ```

But we do have

```
$ wolfictl apk ls  https://apk.cgr.dev/chainguard/x86_64/APKINDEX.tar.gz  --latest | grep unixodbc 
unixodbc-static-2.3.12-r3.apk
unixodbc-2.3.12-r3.apk
unixodbc-doc-2.3.12-r3.apk
unixodbc-dev-2.3.12-r3.apk
unixodbc-config-2.3.12-r3.apk
```

**Comment by imjasonh** [comment]
Not quite: https://github.com/wolfi-dev/os/pull/28350/files 😦

**Comment by xnox** [comment]
> Not quite: https://github.com/wolfi-dev/os/pull/28350/files 😦

Let's just move past that by doing a rebuild to epoch 4 https://github.com/wolfi-dev/os/pull/32153

**Review by xnox — APPROVED** [review]
apk.cgr.dev is up to date with all melange files.

**Pull request merged**
