### PR TITLE
Add hwloc for building NeMo

### PR DESCRIPTION
**Pull request by srishtih**
Fixes:

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [x] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [x] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by srishtih** [comment]
Adding to build Transformer Engine for NeMo https://github.com/chainguard-dev/image-requests/issues/787

**Comment by smoser** [comment]
It looks like maybe you didn't `git add openmpi.yaml` ? All that gets added here is hwloc , and I didn't see a separate open PRfor openmpi.

**Comment by srishtih** [comment]
I am just trying to build hwloc here, I updated the PR title.

**Comment by smoser** [comment]
OK, so #13357 landed.
I updated this to main with the landed change. rebuild happened, failed. 
see https://github.com/wolfi-dev/os/actions/runs/7991918538/job/21824347634?pr=13321

The log shows "Run actions/download-artifact@21e5c25de9cf2ee24742cd3e822327f3be6dd2a3" which is correct as added in #13357 for aarch64 "# v4.1.1"

Ideas, @imjasonh ?

**Review by smoser — APPROVED** [review]
looks good. thank you.

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
Force merging past broken ABI check caused by single-arch package. We'll need to fix that in the future, unblocking this PR for now.

**Comment by mesaglio** [comment]
Hi there ✋ !

Is the vendor force only x86 arch? I see, [alpine](https://git.alpinelinux.org/aports/tree/main/hwloc/APKBUILD#n7) have it to all archs.
@smoser 

We are working to build opencv, and we need this package

**Pull request merged**
