### PR TITLE
Remove wget from default busybox config.

### PR DESCRIPTION
**Pull request by smoser**
Wget is a http/https client.  We have decided to remove it from the default busybox build as simply good hygiene.

Images that need a command line http client have the following options:
 * add curl package
 * add wget package
 * use busybox-full package instead of busybox.

Also note that ssl config option is dropped.  This is because wget is the only thing that was pulling it in.

See also https://github.com/wolfi-dev/os/pull/12583

### CODE REVIEW

**Comment by imjasonh** [comment]
I checked to be sure, and Melange's `fetch` pipeline uses the `wget` package itself, instead of depending on it being provided by `busybox`: https://github.com/chainguard-dev/melange/blob/a298935850e80ecdb2e05c094ac507939b2bca47/pkg/build/pipelines/fetch.yaml#L5

It looks like our Alpine-based `busybox` image relies on wget being provided by busybox, but that's unrelated to this change, since it's the Alpine-based image: https://github.com/chainguard-images/images/blob/f13ca95620c6dd251f421426b96edb87054824cf/images/busybox/config/alpine/main.tf#L14

**Comment by dlorenc** [comment]
I'm sure this will break something but it makes sense anyway.

**Comment by imjasonh** [comment]
We may want to make our images' dev variants include `wget` explicitly after this, and/or make it pull in `busybox-full` instead of just `busybox`

https://github.com/chainguard-images/images-private/blob/450a1910ec6436b9f69f2e607f52e2a9b9a3b589/tflib/publisher/main.tf#L101

**Review by imjasonh — APPROVED** [review]

**Comment by vaikas** [comment]
https://github.com/wolfi-dev/os/issues/9187

**Pull request merged**
