### PR TITLE
chore(chromium): Add busybox and coreutils as runtime deps

### PR DESCRIPTION
**Pull request by EyeCantCU**
Needed by the wrapper

### CODE REVIEW

**Review by mamccorm — DISMISSED** [review]

**Comment by EyeCantCU** [comment]
I had to bump the epoch which I did several minutes ago, but GitHub is slow right now. Not sure if the approval will be dismissed as stale when the PR finally catches up or not unfortunately

**Comment by ajayk** [comment]
is it possible to update to this version mentioned in the update  https://github.com/wolfi-dev/os/pull/14840

**Comment by EyeCantCU** [comment]
> is it possible to update to this version mentioned in the update #14840

It is. Unfortunately it looks like it isn't updating the expected commit. I'll manually update Chromium to match the version in the PR with the expected commit bumped

**Comment by EyeCantCU** [comment]
Added the update to this PR so we get everything in one go rather than waiting on two builds back to back

**Review by mamccorm — APPROVED** [review]

**Comment by EyeCantCU** [comment]
We're running out of space on the update check 😂

**Pull request merged**
