### PR TITLE
git: update to 2.39.1

### PR DESCRIPTION
**Pull request by imjasonh**
https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/
https://lore.kernel.org/git/xmqq7cxl9h0i.fsf@gitster.g/T/#u

Signed-off-by: Jason Hall <jason@chainguard.dev>

### CODE REVIEW

**Review by dlorenc — DISMISSED** [review]

**Review by puerco — DISMISSED** [review]

**Review by dlorenc — DISMISSED** [review]

**Comment by dlorenc** [comment]
No good fix goes unpunished! Looks like you need to run the advisory db updater

**Comment by kaniini** [comment]
It runs automatically on every commit!

**Comment by dlorenc** [comment]
> It runs automatically on every commit!

So we can merge? Why is the linter mad?

**Comment by luhring** [comment]
> So we can merge? Why is the linter mad?

Because there were secfixes entries with no corresponding advisories entries

**Review by dlorenc — APPROVED** [review]

**Review by rawlingsj — APPROVED** [review]

**Review by puerco — APPROVED** [review]

**Pull request merged**
