### PR TITLE
bash: enable system-wide bashrc

### PR DESCRIPTION
**Pull request by shyim**
Enables that bash reads `/etc/bash.bashrc` like any other linux distro and there is now by default a config file to turn on bash completion if installed.

Therefore: `apk add git git-completion bash bash-completion`

and then start a bash shell and git completion just works 😍 

requires https://github.com/wolfi-dev/os/pull/29544 for git

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by justinvreeland** [comment]
This is certainly useful functionality! Would you mind splitting it out into a separate sub-package though, maybe something to the effect of `bash-default-config`. We're not trying to provide the same interactive experience distros provide we're really just compiling software to put into images. I'd rather we didn't distribute configuration, particularly that geared towards interactive use as part of our default package installs.

**Comment by shyim** [comment]
It's nice when we built codespaces/devcontainer image has also some kind of bash completions :).

Keep the bash package like it is and just move the config into a new package?

**Comment by justinvreeland** [comment]
> It's nice when we built codespaces/devcontainer image has also some kind of bash completions :).

I 100% agree.

> Keep the bash package like it is and just move the config into a new package?

Yes please! Ideally putting the configs in separate packages lets us put more extensive/specific configs in and not need to worry about pruning them down the line for whatever reason when they end up in an image as well.

**Comment by shyim** [comment]
Done!. I had to change bash to an mirror, their official page is down for me...

**Review by justinvreeland — APPROVED** [review]

**Pull request merged**
