### PR TITLE
Add py3-tfx-bsl

### PR DESCRIPTION
**Pull request by Dentrax**
Fixes:

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by alexeagle** [comment]
Hello! It looks like I'll come help out to green this one up as soon as we get some contract in place.

**Comment by alexeagle** [comment]
FYI @jamonation I've been trying to help green this one up. Based on your work in https://github.com/wolfi-dev/os/pull/8326 I think this probably has similar problems.

**Comment by jamonation** [comment]
Ah @alexeagle I think it might be an issue with upstream Tensorflow needing to support 3.12 and we're too ahead of things. I found https://github.com/tensorflow/tensorflow/issues/62003 that seems to indicate 3.12 is still a work in progress.

**Comment by alexeagle** [comment]
Yes, totally agree we are trying with a newer python than they support. I assumed the goal with wolfi was to always be on the latest interpreter for security fixes, so it was a design goal to patch up all the packages to work with a newer version.

**Comment by Dentrax** [comment]
Hey @alexeagle @jamonation, thank you for your thoughts!

Could you please check if my _patching_ approach is correct?

I have tried to follow similar approach as you already done here: https://github.com/wolfi-dev/os/pull/8326/files

**Comment by alexeagle** [comment]
I'm not sure what you mean by "approach". Patching the dependencies is likely required unless we build it exactly like the project does on their own CI (ie with the same python version)

I found I had to edit your patch to remove the zeta->m4 portion as the version bump of m4 brought in those changes. It seems like you do have a working technique for creating the patches.

**Pull request closed without merging**
