### PR TITLE
new pkg: dotnet-9

### LINKED ISSUE #33999: [Wolfi Package Request]: dotnet-9
### What software would you like us to add to wolfi-os. Ideally include a URL to the project and its source.

https://github.com/dotnet/dotnet/releases/tag/v9.0.0

### which versions of the software should we include?

_No response_

### Add some justification for why this specific package and versions are important.

dotnet 9 is officially released now.
dotnet 6 has entered EOL

### Please check all that apply

- [X] This package has an un-restrictive license
- [X] The package/versions proposed are actively maintained upstream
- [X] I am interested in adding this package to Wolfi OS myself
- [ ] I am willing to help maintain this package

### PR DESCRIPTION
**Pull request by tuananh**
Fixes: https://github.com/wolfi-dev/os/issues/33999

image

Related:

#### For new package PRs only

- [x] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by tuananh** [comment]
@ajayk  can you take a look?

**Comment by tuananh** [comment]
@xnox friendly ping. Can you take a look at this?

I will provide a subsequent PR to add `dotnet9-bootstrap` so that we can build dotnet-9 from source.

**Comment by xnox** [comment]
> 2024/11/18 11:26:59 INFO Package: dotnet-9: [no-repeated-deps]: package brotli-dev is duplicated in environment (ERROR)

One lint failure!

**Comment by tuananh** [comment]
Fixed

> > 2024/11/18 11:26:59 INFO Package: dotnet-9: [no-repeated-deps]: package brotli-dev is duplicated in environment (ERROR)
> 
> One lint failure!

**Comment by xnox** [comment]
@tuananh =) thank you for this =) but please note we actually have an engineer working on bootstrapping all of these things. I will merge this; but you don't need to get involved in making bootstrap packages as I'd rather have our engineers work on that.

**Review by xnox — APPROVED** [review]

**Pull request merged**
