### PR TITLE
new pkg: gitlab-exporter

### PR DESCRIPTION
**Pull request by tuananh**
Fixes:

Related: https://github.com/chainguard-images/images/issues/566

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

#### For security-related PRs

- [ ] The security fix is recorded in `advisories` and `secfixes`

#### For version bump PRs

- [ ] The `epoch` field is reset to 0
- [ ] Patch source: _patch source here_

### CODE REVIEW

**Comment by tuananh** [comment]
Not sure what's the license value for this license

https://gitlab.com/gitlab-org/gitlab-exporter/-/blob/master/LICENSE

**Comment by rawlingsj** [comment]
> Not sure what's the license value for this license so i set it to "custom"

I'm not sure either, @kaniini wdyt?

**Comment by kaniini** [comment]
I would say it is MIT, but they have added additional text to it

**Comment by rawlingsj** [comment]
This looks like it's been done now https://github.com/wolfi-dev/os/blob/e8302d89df5e6354a5d26129be47c551412bc8c2/gitlab-cng.yaml#L33 - thanks for looking all the same @tuananh

**Pull request closed without merging**
