### PR TITLE
Fixed: llhttp/9.1.3 package update

### LINKED ISSUE #7018: Fix llhttp/9.1.3 package update (#6945)
The auto-update PR for `llhttp/9.1.3` is broken. Check PR #6945 for more details.

_Don't forget to leave a comment if you want to claim this issue for Hacktoberfest._

### PR DESCRIPTION
**Pull request by debasishbsws**
Fixes: #7018
Related: llhttp/9.1.3 package update (Fixes: #6945) 

I think the #6945 pr test was failing because of the Patch that was present there.
In the new version the changes made by the patch is already there in the code.

Though in the log it is saying that patch is skipped but it is failing the pipeline, shouldn't it just skip without failing? 

### For version bump PRs
 - [x] The epoch field is reset to 0

### CODE REVIEW

**Comment by debasishbsws** [comment]
Hey @dlorenc or @erikaheidi the test CI is failing because of soname mismatch
```
time="2023-10-23T05:49:56Z" level=fatal msg="error during command execution: 1 error occurred:\n\t* soname files differ, this can cause an ABI break.  Existing soname files libllhttp.so.8.1.1,
new soname files libllhttp.so.9.1.3: soname version check failed, libllhttp has an existing version 8.1.1 while new package contains a different version 9.1.3.  This can cause ABI failures\n\n"
```
I am not sure what is happening here. what should I do as we are upgrading the version of the package?

**Comment by rawlingsj** [comment]
Hi @debasishbsws - thanks for helping with this.  We have a similar failure on [this](https://github.com/wolfi-dev/os/pull/7051#issuecomment-1775039178) PR.  So that we have confidence that we don't break ABI compatibility with this new update could we bump the epoch of packages that use this?  It looks like the only package that uses this library is https://github.com/wolfi-dev/os/blob/2679b73d42449ad2773ca6ca15ac5982f8d3e9d2/py3-aiohttp.yaml#L42, 

So just need to bump https://github.com/wolfi-dev/os/blob/2679b73d42449ad2773ca6ca15ac5982f8d3e9d2/py3-aiohttp.yaml#L5 in this PR.

**Comment by rawlingsj** [comment]
Yeah it's just to verify that we don't break other packages with this update.

**Comment by rawlingsj** [comment]
@kaniini we'll need to override the failed soname check here.

**Review by kaniini — DISMISSED** [review]

**Comment by ltagliaferri** [comment]
Thank you for this contribution @debasishbsws ! Can you send us an email at deved@chainguard.dev please so we can reward your Hacktoberfest contribution?

**Comment by debasishbsws** [comment]
Hey @ltagliaferri I have send the mail to deved@chainguard.dev with my name and email.

**Pull request merged**
