### PR TITLE
Drop flit-core from pip deps.

### PR DESCRIPTION
**Pull request by smoser**
* Add py/pip-check pipeline for running 'pip check'
*     py3-pip - drop flit-core as a runtime dependency.
    
    Pip itself does not have any imports of flit or flit_core.
    This was added in the pyversions refactor probably because
    of a misunderstood dependency.  Several packages have
    a pyproject entry like wheel does:
    
       pyproject.toml:requires = ["flit_core >=3.8,<4"]
       pyproject.toml:build-backend = "flit_core.buildapi"
    
    And a simple 'pip build' will show a stack trace that doesn't
    actually even leave pip so it appears/appeared that pip
    had a flit_core dep.
    
    Reality is that flit-core should be in the build environment
    of those packages.

 *  bump python projects to rebuild due to flit-core move

### CODE REVIEW

**Comment by smoser** [comment]
I left this as draft for now. I'm locally re-building all things that have 'py3-pip' or 'py3-supported-pip' in their yaml.

**Review by pnasrat — CHANGES_REQUESTED** [review]
Only change runtime dep in py3-pip in this PR

**Review by pnasrat — DISMISSED** [review]
LGTM

Disregard previous comment

**Review by pnasrat — DISMISSED** [review]
LGTM

**Review by pnasrat — APPROVED** [review]
LGTM

**Pull request merged**
