### PR TITLE
use .tar.gz extension as .tar.bz2 are not generate in future versions

### PR DESCRIPTION
**Pull request by rawlingsj**
This means these packages can be updated by the wolfi bot in the future.

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]
Is this worth a lint warning or something?

**Review by imjasonh — APPROVED** [review]
Is this worth a lint warning or something?

**Comment by rawlingsj** [comment]
> Is this worth a lint warning or something?

Not sure TBH, I think it's still a valid extension for some packages, just not these three.  The main reason it was caught was because initially `.tar.bz2` were being created, but the bot updater fails for new versions.  When folks contribute new packages `.tar.bz2` wont be available so they would only use `.tar.gz`

**Comment by rawlingsj** [comment]
> Is this worth a lint warning or something?

Not sure TBH, I think it's still a valid extension for some packages, just not these three.  The main reason it was caught was because initially `.tar.bz2` were being created, but the bot updater fails for new versions.  When folks contribute new packages `.tar.bz2` wont be available so they would only use `.tar.gz`

**Review by kaniini — APPROVED** [review]

**Review by kaniini — APPROVED** [review]

**Pull request merged**
