### PR TITLE
php-8.3: add php provide

### PR DESCRIPTION
**Pull request by shyim**
As the provide is missing, I cannot install php-8.3 + composer togeher right now

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [X] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [X] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by shyim** [comment]
I fixed the provides

**Comment by shyim** [comment]
Pipeline should work now sorry

**Comment by shyim** [comment]
@ajayk (sorry for ping), could we get this merged? You guys are making ads right now using [Laravel with Chainguard](https://www.crowdcast.io/c/learninglabs-apr24) , but it's right now not possible to use the latest PHP version properly with Composer.

**Comment by ajayk** [comment]
There was a similar issue discussed here https://github.com/wolfi-dev/os/pull/10484 

cc: @mattmoor @vaikas

**Comment by shyim** [comment]
Another idea would be to remove the requirement to PHP in `composer` package. It's kinda obvious failure when you run then composer that PHP is missing

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
