### PR TITLE
lint: default wolfi-base in tests

### PR DESCRIPTION
**Pull request by imjasonh**
Also add a lint check that removes it from configs and removes newly empty blocks.

Supercedes https://github.com/wolfi-dev/os/pull/13330

### CODE REVIEW

**Comment by rawlingsj** [comment]
Just a thought on this and there maybe other motivations which make my thought irrelevant but...  sometimes for downstream consumers of packages it can be hard to know what the minimal set of dependencies are. I.e folks should use a `depends` block to include things like bash, busybox etc so if we always install wolfi-base in the test environment, it means we're not testing the depends section if a package requires a shell. So we could end up testing a package with extra default packages that are not installed by default when adding a package.

**Comment by imjasonh** [comment]
> Just a thought on this and there maybe other motivations which make my thought irrelevant but... sometimes for downstream consumers of packages it can be hard to know what the minimal set of dependencies are. I.e folks should use a `depends` block to include things like bash, busybox etc so if we always install wolfi-base in the test environment, it means we're not testing the depends section if a package requires a shell. So we could end up testing a package with extra default packages that are not installed by default when adding a package.

The problem is that _all_ packages _must_ have a shell in order to work at all, because of how melange runs steps. Even if you're just doing `tool command`, melange runs it as `sh -c "tool command"`, so you'll never be able to _not_ have a shell dependency.

**Review by rawlingsj — APPROVED** [review]

**Comment by rawlingsj** [comment]
Ah gotcha - SGTM!

**Review by mattmoor — APPROVED** [review]

**Comment by imjasonh** [comment]
Merging past the tests because this is a purely mechanical cleanup change, and unrelated to pre-existing test failures.

**Pull request merged**
