### PR TITLE
alphabetize runtime / build deps for [a-c]*yaml.

### PR DESCRIPTION
**Pull request by vaikas**
As discussed in: https://github.com/chainguard-dev/yam/issues/27

run the following mechanical cleanup for packages sorting for [a-c]*yaml:
```
yam --sort .environment.contents.packages
yam --sort .package.dependencies.runtime
```

No functional changes, only cosmetic.

### CODE REVIEW

**Comment by luhring** [comment]
If we wanted, we could even define those new sort rules in the repo's [yam config file](https://github.com/wolfi-dev/os/blob/be7d1d4186412c3122a854cc79de7ad454aa482d/.yam.yaml). And that way this sorting would be enforced in CI for future changes, too! And, locally, folks can just run `yam` (no args) and the sorting will be applied according to the configured rules.

We'd just add a new section to the config:

```yaml
sort:
  - ".environment.contents.packages"
  - ".package.dependencies.runtime"
```

**Comment by vaikas** [comment]
Yes! Maybe I got these steps backwards, but my thinking was, fix the existing stuff first (one big hit), then add the rules for pre-checks.

**Comment by luhring** [comment]
That order sounds right to me, and I think it can be the same PR or separated PRs (unless I'm not thinking of something).

Your approach SGTM!

**Review by luhring — DISMISSED** [review]

**Comment by vaikas** [comment]
ooops, I apparently broke something... hang tight.

**Comment by vaikas** [comment]
hm, looks like ncurses failed:
```
2023-08-17T18:06:40.2147759Z 2023/08/17 18:06:40 ERROR: failed to build package. the build environment has been preserved:
2023-08-17T18:06:40.2149181Z ℹ️  x86_64    |   workspace dir: /tmp/melange-workspace-1398621215
2023-08-17T18:06:40.2149587Z ℹ️  x86_64    |   guest dir: /tmp/melange-guest-2601859572
2023-08-17T18:06:40.2149995Z Error: failed to build package: unable to emit package: unable to build final dependencies set: offset 419: expected 
2023-08-17T18:06:40.2150355Z 
2023-08-17T18:06:40.2150635Z 2023/08/17 18:06:40 error during command execution: failed to build package: unable to emit package: unable to build final dependencies set: offset 419: expected 
2023-08-17T18:06:40.2177634Z make[1]: *** [Makefile:73: packages/x86_64/ncurses-6.4_p20230722-r0.apk] Error 1
2023-08-17T18:06:40.2178190Z make[1]: Leaving directory '/__w/os/os'
2023-08-17T18:06:40.2178514Z make: *** [Makefile:68: package/ncurses] Error 2
2023-08-17T18:06:40.2219210Z ##[error]Process completed with exit code 2.
2023-08-17T18:06:40.2307926Z Post job cleanup.

```


But the diff looks right? 🤔 
https://github.com/wolfi-dev/os/pull/4522/files#diff-46e9271bf720bb36250e2cb96afc5004fcad2abd1dda375215cab63918e49a7dR19

ima retry in case it's a flake?

**Comment by vaikas** [comment]
Hm, maybe a rebase is needed? I don't think this failed on the first run? 🤔 
```
time="2023-08-17T18:31:42Z" level=fatal msg="error during command execution: 8 errors occurred:\n\t* package chrony: update found newer version 4.4 compared with package.version 4.3 in melange config\n\t* package cython: update found newer version 3.0.0 compared with package.version 0.29.36 in melange config\n\t* package cmake: update found newer version 3.27.3 compared with package.version 3.27.1 in melange config\n\t* package clickhouse: update found newer version 23.7.4.5 compared with package.version 23.6.2.18 in melange config\n\t* package bank-vaults: update found newer version 1.20.0-dev.3 compared with package.version 1.19.0 in melange config\n\t* package clamav: update found newer version 1.1.1 compared with package.version 1.1.0 in melange config\n\t* package bind: update found newer version 9.18.18 compared with package.version 9.18.17 in melange config\n\t* package cqlsh: update found newer version 4.1.3 compared with package.version 4.1.2 in melange config\n\n"
```

**Comment by vaikas** [comment]
Finally getting back to this:
https://github.com/wolfi-dev/os/pull/5226

Will take care of: https://github.com/wolfi-dev/os/pull/4522#issuecomment-1682728752

**Pull request closed without merging**
