### PR TITLE
Fix CVE GHSA-34jh-p97f-mpxf in kubeflow-pipelines-visualization-server

### PR DESCRIPTION
**Pull request by debasishbsws**
Updated the patch by running pip-compile --output-file=- --resolver=backtracking requirements.in > requirements.txt

### CODE REVIEW

**Comment by debasishbsws** [comment]
This also fix the cve GHSA-248v-346w-9cwc

**Comment by debasishbsws** [comment]
We can fix more in than same PR

**Comment by debasishbsws** [comment]
Others are pending upstream fix

**Comment by debasishbsws** [comment]
Advisory for the rest of the CVE: https://github.com/wolfi-dev/advisories/pull/8244

**Review by hectorj2f — APPROVED** [review]

**Pull request merged**
