### PR TITLE
Do not remove pyc files from python-3.12 and python-3.11

### PR DESCRIPTION
**Pull request by smoser**
This will absolutely increase size of the package, but will improve performance.

Fixes:

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by imjasonh** [comment]
> This will absolutely increase size of the package, but will improve performance.

Can you quantify either or both of the size increase and the performance improvement?

I believe that this is worth doing, but it'd be nice to have numbers to reference.

**Comment by smoser** [comment]
For information, This is the growth in python3.12 due to .pyc files:

```
# find /usr/lib/python3.12/ -name "*.py" | xargs ls -l | awk '{tot += $5}; END { print tot/1024 }'
11324.7

# find /usr/lib/python3.12/ -name "*.pyc" | xargs ls -l | awk '{tot += $5}; END { print tot/1024 }'
11943.8

# find /usr/lib/python3.12/ -name "*.pyc" | wc -l
686

# find /usr/lib/python3.12/ -name "*.py" | wc -l
686
```

So cost of .pyc files includes is roughly the size of the size of .py files
(.pyc files in general are close to the same size as .py file they came from).

**Comment by smoser** [comment]
fwiw, i hadn't seen @imjasonh 's question before i went to put more info here. so I don't consider previous comment on the size increase to answer the performance question.  Google seems not to know much about this, and I don't have a good way to get realistic performance numbers.

There is some info [here](https://peps.python.org/pep-3147/)

> CPython compiles its source code into “byte code”, and for performance reasons, it caches this byte code on the file system whenever the source file has changes. This makes loading of Python modules much faster because the compilation phase can be bypassed. When your source file is foo.py, CPython caches the byte code in a foo.pyc file right next to the source.

It is important to point out that Debian/Ubuntu/Fedora/RHEL all *do* run with pyc files, they just do not ship them in their .deb or .rpm files.  The .pyc files are compiled at install time.

We could potentially do that (change to install-time generation of .pyc files), but it would not have any difference in the end -- the image would still be the same.

The path we're in right now, the image does not have the .pyc files and the filesystem is not writable by the python process, so the python process incurs the cost at start up every time.

**Comment by smoser** [comment]
So here is a bit of info, just to provide something. 

this is in a local-wolfi with python3.12 installed.  As root, I removed all .pyc files:

```
## remove all .pyc files
## run a simple python program (json.tool with -h), which should show --help output
% find /usr/lib/python3.12/ -name "__pycache__" | xargs rm -Rf
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.01s

% find /usr/lib/python3.12/ -name "__pycache__" | xargs rm -Rf 
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.01s

% find /usr/lib/python3.12/ -name "__pycache__" | xargs rm -Rf 
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.00s

% find /usr/lib/python3.12/ -name "__pycache__" | xargs rm -Rf
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.01s

## now we have some .pyc files
% find /usr/lib/python3.12/ -name "*.pyc" | wc -l
37

## run it again without removing the .pyc files
## what changes - its faster now (consistently)
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.03s
user    0m 0.02s
sys     0m 0.00s
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.03s
user    0m 0.02s
sys     0m 0.00s
% time python3.12 -m json.tool -h >/dev/null
real    0m 0.03s
user    0m 0.02s
sys     0m 0.00s


## Now as non-root, so the patsh are not writable
% find /usr/lib/python3.12/ -name "__pycache__" | xargs rm -Rf
% sudo -u nobody /bin/sh
$ time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.00s
$ time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.00s
$ time python3.12 -m json.tool -h >/dev/null
real    0m 0.14s
user    0m 0.13s
sys     0m 0.01s

```

That _is_ startup cost, that is incurred just once, so longer running programs would not be negatively affected.  I'm not sure if there are memory footprint changes due to not reading the cached file.

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
