### PR TITLE
revert datadog to 7.56.2 and fix cves

### PR DESCRIPTION
**Pull request by joshrwolf**
the upgrade to 7.57.x broke functionality. while we figure out the root cause this PR rolls back to the last known good state with patched CVEs

### CODE REVIEW

**Review by debasishbsws — COMMENTED** [review]
Unsure, but should we disable auto-update for sometime until the image gets build, otherwise the automation might update the version to the latest and if the PR build passes we will have the latest version. and image will not get build again.

**Comment by joshrwolf** [comment]
> Unsure, but should we disable auto-update for sometime until the image gets build, otherwise the automation might update the version to the latest and if the PR build passes we will have the latest version. and image will not get build again.

good call!

**Comment by debasishbsws** [comment]
Ahh, We might be looking into wrong package. Though the image build is failing for this one but the CVE has been fixed already
```
grype cgr.dev/chainguard-private/datadog-agent:latest                     ✔ │ 26s  │ 10:09:19 PM 
 ✔ Vulnerability DB                [no update available]
 ✔ Pulled image
 ✔ Loaded image                                                                        cgr.dev/chainguard-private/datadog-agent:latest
 ✔ Parsed image                                                sha256:ab9f9c06ce382a5098a0928263235a61c0ae8b7bb302d2a4c1fc3af4d5205eec
 ✔ Cataloged contents                                                 77c63ed6cebb4f1554f4e75a1db249dc3661868921ef775c51a6d75e517acb63
   ├── ✔ Packages                        [964 packages]
   ├── ✔ File digests                    [22,589 files]
   ├── ✔ File metadata                   [22,589 locations]
   └── ✔ Executables                     [638 executables]
 ✔ Scanned for vulnerabilities     [1 vulnerability matches]
   ├── by severity: 0 critical, 0 high, 1 medium, 0 low, 0 negligible
   └── by status:   1 fixed, 0 not-fixed, 0 ignored
NAME          INSTALLED  FIXED-IN  TYPE    VULNERABILITY        SEVERITY
cryptography  42.0.8     43.0.1    python  GHSA-h4gh-qq45-vh27  Medium
```

We have the CVE in the fips image 😭  we need to downgrade the datadog-agent-fips

**Comment by xnox** [comment]
Maybe it's datadog, maybe it's maybelline. The underlying failure is upon executing the disk check (or maybe any python bridge based checks).

Unpinning updated, and adding such a check to the test pipeline, shows that rebuild is still crashy.

Thus we may have a regression somewhere else, in python, vendored modules, or cgo, or go.

**Comment by xnox** [comment]
> 2024/10/02 13:19:29 WARN snowflake-connector-python 3.11.0 requires cryptography<43.0.0,>=3.1.0, but you have cryptography 43.0.1 which is incompatible. subpackage=datadog-agent-core-integrations

thanks python, glad you carry on after this

**Comment by xnox** [comment]
Ok, now I am happy

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
