### PR TITLE
Fix chartmuseum pulling in glibc

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Comment by dlorenc** [comment]
What's the problem with pulling it in? IIUC melange should auto-detect this then add it to the image as a runtime dependency.

**Comment by imjasonh** [comment]
> What's the problem with pulling it in? IIUC melange should auto-detect this then add it to the image as a runtime dependency.

How does melange auto-detect it? It sounded like `CGO_ENABLED=0` might be the hint that it needed, but I don't even pretend to understand how that works.

**Comment by jdolitsky** [comment]
good question for @kaniini

**Comment by kaniini** [comment]
What is the question, exactly?

**Review by kaniini — APPROVED** [review]

**Pull request merged**
