### PR TITLE
package: perl-mozilla-ca

### PR DESCRIPTION
**Pull request by mesaglio**

### CODE REVIEW

**Comment by mesaglio** [comment]
@ajayk can you help me with this pr? I have https://github.com/wolfi-dev/os/pull/37470, https://github.com/wolfi-dev/os/pull/37468 too

**Comment by ajayk** [comment]
@mesaglio can you please add a basic test

**Comment by mesaglio** [comment]
Is [this](https://github.com/wolfi-dev/os/pull/37470/files#diff-6c1861f0ce14e150b9a5b5b4ad9537c63c25ad5d8ffa292ae4f407b2b795598bR46) test ok?

**Comment by mesaglio** [comment]
@ajayk 🏓

**Review by ajayk — APPROVED** [review]

**Pull request merged**
