### PR TITLE
binaryen.yaml: Add openssf-options

### PR DESCRIPTION
**Pull request by justinvreeland**

### CODE REVIEW

**Review by ajayk — DISMISSED** [review]

**Review by dannf — CHANGES_REQUESTED** [review]
weird, it builds fine for me w/o this change

**Comment by justinvreeland** [comment]
> weird, it builds fine for me w/o this change

Huh, ok maybe it fixed itself in the meantime pushed a version without the override if it works I'll just close this.

**Comment by dannf** [comment]
Maybe 2c43fa5443b10c82957dad4c651874313aa04f4d fixed it

**Comment by justinvreeland** [comment]
Ahh yeap that seem likely, awesome.

**Pull request closed without merging**
