### PR TITLE
Add kuberlr v0.5.2 package

### PR DESCRIPTION
**Pull request by farcop**
#### For new package PRs only
- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

### CODE REVIEW

**Comment by farcop** [comment]
@ajayk Hi! Could you please rerun checks pipelines after linting was fixed?

**Comment by ajayk** [comment]
> @ajayk Hi! Could you please rerun checks pipelines after linting was fixed?

Looks good now , i you can add basic test we can merge this asap ,  you can look for `test` pipeline i added a sample below 

```
test:
  pipeline:
    - runs: |
        kuberlr version  || exit 1
        kuberlr --help
 ````

**Review by ajayk — CHANGES_REQUESTED** [review]
can you please add a basic test

**Comment by farcop** [comment]
@ajayk Done. Thanks!

**Review by ajayk — APPROVED** [review]

**Pull request merged**
