### PR TITLE
Add/golang 1.22 fips

### PR DESCRIPTION
**Pull request by smoser**
Fixes:

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by smoser** [comment]
This took an idea from https://github.com/wolfi-dev/os/pull/15486 to try and see if we the binary we build by go-fips looks like it will use libssl.

@imjasonh seems reasonable to get some of that testing done in package test?

**Comment by ajayk** [comment]
@smoser looks good !!! 🎉

**Review by ajayk — DISMISSED** [review]

**Comment by dlorenc** [comment]
Nice work!

**Comment by smoser** [comment]
@xnox , your input is requested here, especially on the 'extras' patches, as those changed significantly from their 1.21 counterparts.

**Comment by smoser** [comment]
closing this for now.

**Pull request closed without merging**
