### PR TITLE
Promote Node.js 20 to LTS.

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
The "go live" for this (according to Bard) is 10/24, this is simply preparatory.

**Comment by ajayk** [comment]
superseded by https://github.com/wolfi-dev/os/pull/7313

**Comment by mattmoor** [comment]
@ajayk no, it'll just need another rebase 🙃

**Review by ajayk — APPROVED** [review]

**Comment by mattmoor** [comment]
Confirming that 20.9 is LTS: https://github.com/nodejs/node/releases/tag/v20.9.0

**Pull request merged**
