### PR TITLE
py3-urllib3/2.0.1 package update - also enable auto updates and inclu…

### LINKED ISSUE #1704: py3-urllib3/2.0.1 new package update

### PR DESCRIPTION
**Pull request by rawlingsj**
…de `ignore-regex-patterns` to ignore strange upstream version pattern for alpha releases

fixes: #1704

#### For version bump PRs
- [x] The `epoch` field is reset to 0

### CODE REVIEW

**Comment by rawlingsj** [comment]
CI failure
```
'/home/build/setup.py': [Errno 2] No such file or directory
```

A few other packages have had this, to fix those I switched to using pip, i.e 
```
pip install . --prefix=/usr --root=${{targets.destdir}}
```
however py3-urllib3 is failing for a different reason now when building locally
```
File "/usr/lib/python3.11/zipfile.py", line 390, in __init__
⚠️  aarch64   |           raise ValueError('ZIP does not support timestamps before 1980')
⚠️  aarch64   |       ValueError: ZIP does not support timestamps before 1980
```

FWIW this is the melange config I have so far...

```yaml
package:
  name: py3-urllib3
  version: 2.0.1
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/urllib3/urllib3.git
      tag: ${{package.version}}
      expected-commit: b85e93d619a323b92c2954da852857e0119d71b8

  - runs: pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - (\d+\.\d+)\.\da\d+ # urllib3 releases alpha versions with a suffix "a" followed by a digit, let's ignore these
  github:
    identifier: urllib3/urllib3
```

**Review by jdolitsky — DISMISSED** [review]

**Comment by jdolitsky** [comment]
i've seen this exact issue before with pip install, and it can be fixed by hardcoding an epoch. something like
```
export SOURCE_DATE_EPOCH=315532800 && pip install
```

**Comment by rawlingsj** [comment]
ooh! lemme try that here now

**Comment by rawlingsj** [comment]
It worked locally - thanks @jdolitsky!

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
