### PR TITLE
Another batch of updates to python packages to add 3.13.

### PR DESCRIPTION
**Pull request by smoser**

### CODE REVIEW

**Comment by smoser** [comment]
These were just made by running a python program [here](https://gist.github.com/smoser/7da4ed38fb06e80d199ce28e07c20d1b/4e0fbcaffe2276d45b9baf0e44cd295c0ea482ec#file-py-versions) ([raw](https://gist.githubusercontent.com/smoser/7da4ed38fb06e80d199ce28e07c20d1b/raw/4e0fbcaffe2276d45b9baf0e44cd295c0ea482ec/py-versions))

**Review by xnox — DISMISSED** [review]

**Review by justinvreeland — DISMISSED** [review]

**Review by imjasonh — DISMISSED** [review]

**Comment by smoser** [comment]
booo... elastic build worked but GHA failed?
I'll look at that.

**Comment by smoser** [comment]
Oh. actually, good. c-i caught that some things were not intsallable.. I did _not_ test that, and neither did/does the elastic builds.
I'll fix.

**Comment by justinvreeland** [comment]
It looks like caught overlapping binaries when installing the supported packages which is the point of having a test install for those packages 🥳

**Review by justinvreeland — DISMISSED** [review]

**Review by justinvreeland — APPROVED** [review]

**Comment by smoser** [comment]
I'm closing this. it seems that elastic builds build order isn't great, so a mega-pr here with inter-dependent packages doesn't seem to be working.

**Pull request closed without merging**
