### PR TITLE
update libjpeg-turbo to 3.0.0

### PR DESCRIPTION
**Pull request by ajayk**

### CODE REVIEW

**Review by dlorenc — COMMENTED** [review]
Do we expect any breakages as part of the major version bump? Maybe we should test a few dependent builds too.

**Comment by ajayk** [comment]
> Do we expect any breakages as part of the major version bump? Maybe we should test a few dependent builds too.

2.1.91 was also (3.0 beta 2) https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.1.91

and there are  7 significant changes compared to 3.0 beta2 here https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.0

**Comment by ajayk** [comment]
I ran some dependent builds for libjpeg-turbo
- tiff
- libwebp
- guacamole-server

 https://gist.github.com/ajayk/366377c8a40857fd4ff0c52235fe174b

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
Nice!

**Comment by kaniini** [comment]
Should be fine, no ABI breaks as far as I can tell.

**Pull request merged**
