### PR TITLE
Also add no-store to the withdraw job.

### PR DESCRIPTION
**Pull request by dlorenc**
Follow up to https://github.com/wolfi-dev/os/pull/955

Fixes:

Related:

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @rawlingsj - I think this failure is a bug.

**Comment by rawlingsj** [comment]
yeah we can ignore these failures
```
	* failed to create a version from package python-3.12: 3.12.0_alpha6: Malformed version: 3.12.0_alpha6
	* failed to create a version from package openssh: 9.3_p1.  Error: Malformed version: 9.3_p1
```
there's two open issues to cover them
https://github.com/wolfi-dev/os/issues/920
https://github.com/wolfi-dev/os/issues/923

The check is not a github required check so this should merge...

**Comment by rawlingsj** [comment]
hmm that's annoying - even though the update check isn't a "required" check in the branch protection rules it still seems to block.  Let's merge this by overriding and will need to find a better way.

**Review by rawlingsj — APPROVED** [review]

**Comment by rawlingsj** [comment]
Oh maybe it would have auto merged - it just wasn't approved.

**Pull request merged**
