### PR TITLE
lame: add package

### PR DESCRIPTION
**Pull request by lpcalisi**
add lame to add libmp3lame support to ffmpeg

### CODE REVIEW

**Comment by lpcalisi** [comment]
@xnox [lame](https://release-monitoring.org/project/12523/) have not any recent release for the last four years, but all main distros have it ([ubuntu](https://packages.ubuntu.com/search?keywords=lame), [alpine](https://release-monitoring.org/project/12523/)). What do you think about putting it on wolfi?

**Comment by lpcalisi** [comment]
@smoser could you give your feedback here too? Thanks

**Review by smoser — DISMISSED** [review]
fix the lint and lgtm.

**Comment by lpcalisi** [comment]
> fix the lint and lgtm.

thanks you!

**Comment by xnox** [comment]
The quality of this software is obviously degrading. On the other hand mp3 is still popular in the virtual voicemail settings. So on the balance, it is probably more useful to have in, than out.

**Review by smoser — APPROVED** [review]

**Pull request merged**
