### PR TITLE
add ninja pkg

### PR DESCRIPTION
**Pull request by tuananh**
Signed-off-by: Tuan Anh Tran <me@tuananh.org>

### CODE REVIEW

**Comment by kaniini** [comment]
We use `samurai` to provide ninja.  Is there a reason why Ninja itself is required?

**Comment by tuananh** [comment]
> 

i'm not well-versed in this topic. i just saw some of hte package required ninja when building. not sure what's the pros & cons of samurai vs ninja.

the top link on this topic is apaprently written by you :D 

https://lists.alpinelinux.org/~alpine/devel/%3CCAAOiGNwnzTomzOQ6YjH3t7VHmbfMRZUNXap8GM0Gy_mGS7aKhg%40mail.gmail.com%3E

**Comment by kaniini** [comment]
I think we should avoid Ninja, personally, as samurai does everything functionally required for building the distribution.  Ninja does however have some tools that samurai does not yet implement, so there may be an argument for providing it in the future.

**Comment by rawlingsj** [comment]
I've been using the `samurai` package when needing `Ninja` and it's been working great.  Let's close this PR and we can always reopen if there's a need.

**Pull request closed without merging**
