### PR TITLE
add openjdk-15, 16, and updated 17

### PR DESCRIPTION
**Pull request by joshrwolf**
new packages: openjdk-15 and 16

updated packages: openjdk-17, zookeeper, keycloak, jenkins, cloudwatch-exporter

this brings openjdk17 up to par with the updated way we're packaging openjdk

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [x] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [x] REQUIRED - The version of the package is still receiving security updates
- [x] REQUIRED - The package is added to `packages.txt`

### CODE REVIEW

**Comment by patflynn** [comment]
can we update the java homes and test the [downstream packages](https://github.com/search?q=repo%3Awolfi-dev%2Fos%20openjdk-17&type=code)?

**Comment by joshrwolf** [comment]
> can we update the java homes and test the [downstream packages](https://github.com/search?q=repo%3Awolfi-dev%2Fos%20openjdk-17&type=code)?

in this PR or in follow ups? I mostly just wanted this in CI to check for any fun CI only errors again

**Comment by patflynn** [comment]
I would do this as part of this PR to make sure we find out if we break any of those packages before we merge.

**Comment by joshrwolf** [comment]
I restructured the `packages.txt` dependencies manually for now, but this should hopefully be the last blocker before we can get smart with @deitch's dag!

**Comment by joshrwolf** [comment]
the wolfictl update check is expected to fail, both for jenkins ([ref](https://github.com/wolfi-dev/os/pull/2095/files#diff-81fd7bbc8686780d333edd3f65232ac48713e9ab7b781cd00fcea66d97967baeL56)) and openjdk-17 mangled package version

**Pull request merged**
