### PR TITLE
Change the CI builds to sync only the necessary files rather than the…

### PR DESCRIPTION
**Pull request by dlorenc**
… entire bucket.

Fixes:

Related:

### CODE REVIEW

**Review by imjasonh — DISMISSED** [review]

**Comment by dlorenc** [comment]
This reduces the sync from every package/version ever built to only the latest ones. The current math is a drop from 62GB to 4GB.

**Comment by dlorenc** [comment]
This proves that nothing extra gets built: https://github.com/wolfi-dev/os/actions/runs/4651386328/jobs/8230960375

I'll push a few PRs (not intended for merge) on top of this branch to test that bumps do get built correctly.

**Comment by dlorenc** [comment]
https://github.com/wolfi-dev/os/pull/1112
https://github.com/wolfi-dev/os/pull/1111

**Comment by dlorenc** [comment]
Ugh, this doesn't work because it misses subpackages. Need to think more on it...

**Comment by tuananh** [comment]
> Ugh, this doesn't work because it misses subpackages. Need to think more on it...

dag can help here? generate a full deps tree and sync those?

**Comment by kaniini** [comment]
Obsoleted by #1118.

**Pull request closed without merging**
