### PR TITLE
protoc-gen-go-grpc: fix build to compile the CLI

### PR DESCRIPTION
**Pull request by vito**
Related: https://github.com/wolfi-dev/os/pull/19132 (introduced regression)

Currently the `protoc-gen-go-grpc` package installs the _library_ as `/usr/bin/protoc-gen-go-grpc` instead of the CLI as it did before. Seems like a simple oversight from the broader refactor.

### CODE REVIEW

**Review by ajayk — CHANGES_REQUESTED** [review]
needs to epoch bump

**Comment by vito** [comment]
@ajayk Whoops, fixed - thanks for the quick review!

**Review by ajayk — COMMENTED** [review]
Can we add a basic test , here is something you can use which avoids further breakage of packages 

```
test:
  pipeline:
    - runs: |
        protoc-gen-go-grpc --version
```

**Comment by vito** [comment]
@ajayk Absolutely - just added, thanks. Not sure how to run the test, but I manually verified by following the `CONTRIBUTING.md`. :+1:

**Comment by ajayk** [comment]
> @ajayk Absolutely - just added, thanks. Not sure how to run the test, but I manually verified by following the `CONTRIBUTING.md`. 👍

if you check the builds logs [here](https://github.com/wolfi-dev/os/actions/runs/9103175195/job/25024493396?pr=19530) is a an example of running in a test , I will add the running tests to the docs 
```
/usr/bin/melange test ./protoc-gen-go-grpc.yaml --source-dir ./protoc-gen-go-grpc --repository-append ./packages --keyring-append local-melange.rsa.pub --arch aarch64 --pipeline-dirs ./pipelines/ --repository-append https://packages.wolfi.dev/os --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub --test-package-append wolfi-base --debug --runner docker --log-policy builtin:stderr
```

Test output here 
```
2024/05/15 21:57:49 INFO running the main test pipeline
2024/05/15 21:57:49 WARN + export 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
2024/05/15 21:57:49 WARN + '[' -d /home/build ]
2024/05/15 21:57:49 WARN + cd /home/build
2024/05/15 21:57:49 WARN + protoc-gen-go-grpc --version
2024/05/15 21:57:49 INFO protoc-gen-go-grpc 1.3.0
2024/05/15 21:57:49 WARN + exit 0
2024/05/15 21:57:49 INFO pod 84454af44d1f07a3136938b65797bfb99025f299466d2c6e6beed9bd50c8aced terminated
```

**Review by ajayk — APPROVED** [review]

**Pull request merged**
