### PR TITLE
test/pkgconf pipelines for all dev packages that currently succeed

### PR DESCRIPTION
**Pull request by dustinkirkland**
This set of tests uses the new test/pkgconf pipeline.

All ~263 of these are confirmed passing right now in make test/*

### CODE REVIEW

**Review by justinvreeland — DISMISSED** [review]
Love adding more tests

**Review by justinvreeland — DISMISSED** [review]

**Review by joshrwolf — DISMISSED** [review]
this lgtm, but similar to the rest of these batches it'll need a force merge. cc @mamccorm

**Comment by dustinkirkland** [comment]
@joshrwolf @murraybd @xnox Is there anything else I need to do here?  I'd love to get this merged, so that I can start working on the next batch...

**Comment by murraybd** [comment]
@dustinkirkland My investigation indicates that the CI failure is just with cyrus-sasl failing to build and I'll have an independent fix for that shortly. So if you just drop the test changes for cyrus-sasl I'll include that in a PR fixing the build failure.

**Comment by dustinkirkland** [comment]
Sweet!  Done!

**Comment by xnox** [comment]
Automatic dependencies have landed. I would rather do epoch bump-full rebuilds for all the things. Because then the next batch should be enabled strict pipeline checks for all packages.

**Comment by dustinkirkland** [comment]
Okay -- so I'll do the work to do this (epoch bumps) -- if both @murraybd and @joshrwolf agree?

**Review by joshrwolf — APPROVED** [review]
like the other batches of these test only changes, we're not bumping the epoch here so this doesn't trigger a package build in postsubmit, so I'm +1 for force merging this in and catching any errors (which should be only due to discrepancies in our local/prod build environments) in post

**Review by xnox — APPROVED** [review]
Test only change.

**Comment by imjasonh** [comment]
Force merging because some packages fail to rebuild now. We'll test everything after this and fix up anything that fails.

**Pull request merged**
