### PR TITLE
use python version so we dont have to manually update site-pkg path

### PR DESCRIPTION
**Pull request by tuananh**
use python version from `_py3ver=$(python3 -c 'import sys; print("{}.{}".format(sys.version_info.major, sys.version_info.minor))')` => `3.12` so that we don't forget to update site-packages path when rebuilding py3-* pkg with new version of python.
 
Fixes:

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by tuananh** [comment]
the update check failure seems to be false alarm since 15.0.0 of pyarrow is a dev release

**Comment by tuananh** [comment]
@ajayk  can you help review this?

**Comment by ajayk** [comment]
Looks good I just want to get another set of reviewers to look this 

@imjasonh @rawlingsj

**Comment by tuananh** [comment]
@rawlingsj can you take a look at this?

**Review by rawlingsj — APPROVED** [review]

**Pull request merged**
