### PR TITLE
Add rust-1.79

### PR DESCRIPTION
**Pull request by andresmargalef**
Add new version 1.79 of rust.

### CODE REVIEW

**Comment by ajayk** [comment]
Thanks for your contribution usually adding a new version of rust will be handled by a bot example here https://github.com/wolfi-dev/os/issues/18495

**Comment by andresmargalef** [comment]
Hi @ajayk, should I close this PR? when does that bot run?

**Comment by ajayk** [comment]
@andresmargalef I will add these to our contributing guide , here is the PR if you like to amend some changes https://github.com/wolfi-dev/os/pull/22097/

**Comment by andresmargalef** [comment]
> @andresmargalef I will add these to our contributing guide , here is the PR if you like to amend some changes #22097

I will close this and already left a comment in the other PR.

**Pull request closed without merging**
