### PR TITLE
Libreoffice build!

### PR DESCRIPTION
**Pull request by dlorenc**
This builds and runs, but I haven't done extensive testing.

Note that i was getting build failures using the latest release tag, but not on main. Haven't debugged yet.

### CODE REVIEW

**Comment by developer-guy** [comment]
@dlorenc just as a side note, Gotenborg uses a tool called `unoconverter` which looks specific directories for LibreOffice:

- https://github.com/gotenberg/unoconverter/blob/main/unoconv

**Comment by developer-guy** [comment]
Hi Dan, do you still work on this PR? I need libreoffice for my gotengorg image 🙏

**Comment by dlorenc** [comment]
> Hi Dan, do you still work on this PR? I need libreoffice for my gotengorg image 🙏

No - you can grab it from here!

**Comment by developer-guy** [comment]
Advisory created for the CVE:

- https://github.com/wolfi-dev/advisories/pull/1529

**Pull request closed without merging**
