### PR TITLE
Update clang to provide clang=<version>

### PR DESCRIPTION
**Pull request by justinvreeland**
Also paramterise and remove the clang-dev package which isn't needed anymore.

Fixes: https://github.com/chainguard-dev/internal-dev/issues/1642

### CODE REVIEW

**Comment by justinvreeland** [comment]
@xnox This is probably of interest to you

**Comment by xnox** [comment]
Can use elastic build up listed repo, to figure out what the two test failures are.

**Comment by xnox** [comment]
Can use elastic build published repo, to figure out what the two test failures are? As packages are all built there.

**Comment by justinvreeland** [comment]
> Can use elastic build published repo, to figure out what the two test failures are? As packages are all built there.

Ahh this is kind of annoying. I don't know if something changed but it looks like on linux melange/bwrap doesn't mount /sys so stress-ng tests don't work. 

`2024/10/16 11:56:50 INFO stress-ng: error: [3] no CPUs found in /sys/devices/system/cpu name="Test CPU stressor"`

I'm not sure I understand the point of that test but it's there in both snmalloc and scudo-malloc.

**Comment by xnox** [comment]
Thanks! I can poke it. I am on good terms with stressng and its author.

**Review by xnox — APPROVED** [review]

**Pull request merged**
