### PR TITLE
BUGFIX: Add ignore-regex to update block for py3-pendulum

### PR DESCRIPTION
**Pull request by jspeed-meyers**
Fix the update error associated with https://github.com/wolfi-dev/os/pull/6309

These patterns ignore alpha and beta releases.

@rawlingsj: Are these the regular expressions you expected?

Also, I think the `yam` formatting changed a number of other lines. I didn't intend to change those lines. `yam` forced me :) If you want me to revert those formatting changes, please let me know.

### CODE REVIEW

**Comment by jspeed-meyers** [comment]
Hmm, there seems to be a build problem unassociated the update block change. Investigating...

**Comment by jspeed-meyers** [comment]
I get some form of this error over and over. I broke it into different lines to make it easier to read.

```
Error: failed to build package: unable to build guest:
unable to generate image: installing apk packages:
installing packages: installing py3.12-installer:
unable to install files for pkg py3.12-installer: unable to install file over existing one, different contents:
usr/lib/python3.12/site-packages/installer-0.7.0.dist-info/RECORD
```

I think `poetry` and `installer` are stomping on each other's files. I would need some help to debug further. Apologies. :)

**Comment by rawlingsj** [comment]
Yeah we're still in the process of rolling out a large python 3.12 upgrade which might be affecting this.  Let's try a quick rebase to see if that helps initially, if not we can dig into it.

**Comment by rawlingsj** [comment]
closing as fixed as part of another PR that was fixing the build https://github.com/wolfi-dev/os/pull/6890/files#diff-f02af7e55cbf3aada9f2d0f82f56dbc3cd44e5eaec08a1fe1c52055f91a84ad2R59-R61

thanks for looking at this though @jspeed-meyers!

**Pull request closed without merging**
