### PR TITLE
superset GHSA-f9vj-2wh5-fj8j/GHSA-q34m-jh98-gwm2

### PR DESCRIPTION
**Pull request by jamie-albert**
Update the version of Werkzeug from 3.0.3 to 3.0.6, patch not required after testing with as pip install during backend build pipeline uses the correct version. Remaining CVEs are expected and advisories exist.

### CODE REVIEW

**Review by philroche — DISMISSED** [review]

**Comment by philroche** [comment]
@jamie-albert approved but

> patch not required after testing with as pip install during backend build pipeline uses the correct version. Remaining CVEs are expected and advisories exist

What patch are you referring to?

**Comment by jamie-albert** [comment]
Epoch needed to be bumped to higher than [attempted remediation](https://github.com/wolfi-dev/os/commit/fb0045e2bb0942a50b7d58d775d00820763f916e) that was [reverted here](https://github.com/wolfi-dev/os/commit/607268a34baaada3b7e757d98ddfc5c075611d27). The r5 is still being hosted so we need to build higher than that revision number

**Comment by jamie-albert** [comment]
> @jamie-albert approved but
> 
> > patch not required after testing with as pip install during backend build pipeline uses the correct version. Remaining CVEs are expected and advisories exist
> 
> What patch are you referring to?

In this case we could have either bumped the dependency version via a patch or pip install. The pip install approach worked so I opted to go with that instead.

**Comment by jamie-albert** [comment]
Needed to change version reference from tags to releases. See comment left in this package build failure: https://github.com/wolfi-dev/os/pull/33982#issuecomment-2471877181

**Comment by jamie-albert** [comment]
package update config check is invalid, see this: https://github.com/wolfi-dev/os/pull/33982#issuecomment-2471877181

**Review by philroche — APPROVED** [review]

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
