### PR TITLE
package: py3-pipdetree

### PR DESCRIPTION
**Pull request by mesaglio**

### CODE REVIEW

**Comment by mesaglio** [comment]
@pnasrat what do you think?

**Review by pnasrat — CHANGES_REQUESTED** [review]
Because this package is a binary the use of py3-supported for multi-python support doesn't work in this PR as the packages are not co-installable.  

Unlike pip (which provides a report option that can also be used for dep analysis) or the PEP517 and PEP518 build tools this doesn't need to be co-installable.

Just make this a regular packaged py3-pipdeptree with dependencies on py3-pip and python-3 to make it 3.12 only.



```
apk add x86_64/py3.12-pipdeptree-2.23.1-r0.apk 
ERROR: unable to select packages:
  py3.10-pip-24.2-r0:
    conflicts: py3.12-pip-24.2-r0[cmd:pip3=24.2-r0] py3.12-pip-24.2-r0[cmd:pip=24.2-r0]
    satisfies: py3.10-pipdeptree-2.23.1-r0[py3.10-pip]
  py3.10-pipdeptree-2.23.1-r0:
    conflicts: py3.12-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0]
    satisfies: world[py3.10-pipdeptree><Q14iWCF0B55zyUmEo6DA/0l5BKzZ8=]
  py3.12-pip-24.2-r0:
    conflicts: py3.10-pip-24.2-r0[cmd:pip3=24.2-r0] py3.10-pip-24.2-r0[cmd:pip=24.2-r0]
    satisfies: py3.12-pipdeptree-2.23.1-r0[py3.12-pip]
  py3.12-pipdeptree-2.23.1-r0:
    conflicts: py3.10-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0]
    satisfies: world[py3.12-pipdeptree><Q1GHWlLRVpOfr9s3EAOTkRYI1aZkk=]
```

```console
 apk add x86_64/py3-supported-pipdeptree-2.23.1-r0.apk 
ERROR: unable to select packages:
  py3.10-pip-24.2-r0:
    conflicts: py3.11-pip-24.2-r0[cmd:pip3=24.2-r0] py3.12-pip-24.2-r0[cmd:pip3=24.2-r0] py3.11-pip-24.2-r0[cmd:pip=24.2-r0]
               py3.12-pip-24.2-r0[cmd:pip=24.2-r0]
    satisfies: py3.10-pipdeptree-2.23.1-r0[py3.10-pip]
  py3.10-pipdeptree-2.23.1-r0:
    conflicts: py3.11-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0] py3.12-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0]
    satisfies: world[py3.10-pipdeptree><Q14iWCF0B55zyUmEo6DA/0l5BKzZ8=] py3-supported-pipdeptree-2.23.1-r0[py3.10-pipdeptree]
  py3.11-pip-24.2-r0:
    conflicts: py3.10-pip-24.2-r0[cmd:pip3=24.2-r0] py3.12-pip-24.2-r0[cmd:pip3=24.2-r0] py3.10-pip-24.2-r0[cmd:pip=24.2-r0]
               py3.12-pip-24.2-r0[cmd:pip=24.2-r0]
    satisfies: py3.11-pipdeptree-2.23.1-r0[py3.11-pip]
  py3.11-pipdeptree-2.23.1-r0:
    conflicts: py3.10-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0] py3.12-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0]
    satisfies: py3-supported-pipdeptree-2.23.1-r0[py3.11-pipdeptree]
  py3.12-pip-24.2-r0:
    conflicts: py3.10-pip-24.2-r0[cmd:pip3=24.2-r0] py3.11-pip-24.2-r0[cmd:pip3=24.2-r0] py3.10-pip-24.2-r0[cmd:pip=24.2-r0]
               py3.11-pip-24.2-r0[cmd:pip=24.2-r0]
    satisfies: py3.12-pipdeptree-2.23.1-r0[py3.12-pip]
  py3.12-pipdeptree-2.23.1-r0:
    conflicts: py3.10-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0] py3.11-pipdeptree-2.23.1-r0[cmd:pipdeptree=2.23.1-r0]
    satisfies: py3-supported-pipdeptree-2.23.1-r0[py3.12-pipdeptree]
```

**Comment by mesaglio** [comment]
Hi @pnasrat, thanks for the comments.

I have a question, if we dont make this supporter over all python versions then `pipdtree` only can view the site-packages of last `python3` version no? 

What's happend if I need to use `pipdeptree` on `python3.11` image?

**Comment by mesaglio** [comment]
Hi @pnasrat, thanks for the comments.

I have a question, if we dont make this supporter over all python versions then `pipdtree` only can view the site-packages of last `python3` version no? 

What's happend if I need to use `pipdeptree` on `python3.10` image?

Example:
```terminal
c4cd54b79e1a:/work/packages# apk add python-3.10 py3.10-pip aarch64/py3-pipdeptree-2.23.1-r0.apk
fetch https://packages.wolfi.dev/os/aarch64/APKINDEX.tar.gz
(1/19) Installing libbz2-1 (1.0.8-r8)
(2/19) Installing libexpat1 (2.6.2-r1)
(3/19) Installing libffi (3.4.6-r3)
(4/19) Installing gdbm (1.24-r0)
(5/19) Installing xz (5.6.2-r0)
(6/19) Installing libgcc (13.3.0-r2)
(7/19) Installing libstdc++ (13.3.0-r2)
(8/19) Installing mpdecimal (4.0.0-r2)
(9/19) Installing ncurses-terminfo-base (6.5_p20240629-r0)
(10/19) Installing ncurses (6.5_p20240629-r0)
(11/19) Installing readline (8.2-r7)
(12/19) Installing sqlite-libs (3.45.1-r1)
(13/19) Installing python-3.12-base (3.12.4-r1)
(14/19) Installing py3-pipdeptree (2.23.1-r0)
(15/19) Installing python-3.10-base (3.10.14-r4)
(16/19) Installing py3.10-setuptools (72.1.0-r0)
(17/19) Installing py3.10-pip-base (24.2-r0)
(18/19) Installing py3.10-pip (24.2-r0)
(19/19) Installing python-3.10 (3.10.14-r4)
OK: 120 MiB in 33 packages
c4cd54b79e1a:/work/packages# pip3 install requests
Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)
Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (138 kB)
Downloading idna-3.7-py3-none-any.whl (66 kB)
Downloading urllib3-2.2.2-py3-none-any.whl (121 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.7.4 charset-normalizer-3.3.2 idna-3.7 requests-2.32.3 urllib3-2.2.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
c4cd54b79e1a:/work/packages# pipdeptree
Traceback (most recent call last):
  File "/usr/bin/pipdeptree", line 5, in <module>
    from pipdeptree.__main__ import main
ModuleNotFoundError: No module named 'pipdeptree'
```
I understand `pipdeptree` is using `/usr/bin/python3` as shebang but is `python3.10` and `gpep517` install under `usr/lib/python3.12/site-packages` 😢

**Pull request closed without merging**
