### PR TITLE
gcc-12: add C and C++ tests

### PR DESCRIPTION
**Pull request by xnox**
A recent update of gcc-12 resulted in incorrect runtime SCA
dependencies which caused compilers to not work at all. Add tests that
exercise both frontend and underlying compiler binaries to ensure they
are operation and are able to compile C and C++ code.

This is a smoketest, but would have caught the breakage in gcc-12
update.

Epoch bump not needed for test only change, as presubmit will rebuild
and tests will be executed against current builds.

### CODE REVIEW

**Review by smoser — CHANGES_REQUESTED** [review]
Can you grab https://github.com/xnox/os/pull/6/files changes also?
(and then the `yam` fix :cry: )

**Comment by smoser** [comment]
https://github.com/xnox/os/pull/7

**Comment by smoser** [comment]
hm..

> [xnox#7](https://github.com/xnox/os/pull/7)

I think this is good now.  but when I run `make test/gcc-12`

```
$ make test/gcc-12
yamlfile is gcc-12.yaml
Testing package gcc-12 with version gcc-12-12.4.0-r1 from file gcc-12.yaml
/home/smoser/go/bin/melange test gcc-12.yaml --repository-append /home/smoser/src/wolfi/os/packages --keyring-append local-melange.rsa.pub --arch x86_64 --pipeline-dirs ./pipelines/ --repository-append https://packages.wolfi.dev/os --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub --test-package-append wolfi-base --debug  --source-dir ./gcc-12/
2024/07/11 20:51:22 INFO evaluating pipelines for package requirements
..
2024/07/11 20:51:22 INFO installing glibc-locale-posix (2.39-r7)
2024/07/11 20:51:22 INFO installing glibc (2.39-r7)
2024/07/11 20:51:22 INFO installing libgcc (13.3.0-r0)
2024/07/11 20:51:22 INFO installing libstdc++ (13.3.0-r0)
2024/07/11 20:51:22 INFO installing gmp (6.3.0-r2)
2024/07/11 20:51:22 INFO installing libstdc++-12-dev (12.4.0-r1)
2024/07/11 20:51:22 INFO installing mpfr (4.2.1-r4)
2024/07/11 20:51:22 INFO installing mpc (1.3.1-r4)
2024/07/11 20:51:22 INFO installing isl (0.26-r4)
2024/07/11 20:51:22 INFO installing binutils (2.42-r2)
2024/07/11 20:51:22 INFO installing gcc-12 (12.4.0-r1)
2024/07/11 20:51:22 INFO installing libxcrypt (4.4.36-r7)
...
2024/07/11 20:51:25 INFO running the main test pipeline
2024/07/11 20:51:25 INFO running step "Check basic usage of top level & libexec binaries"
2024/07/11 20:51:25 WARN + '[' -d /home/build ]
2024/07/11 20:51:25 WARN + cd /home/build
2024/07/11 20:51:25 WARN + gcc-12 --version
2024/07/11 20:51:25 WARN + grep 12.4.0
2024/07/11 20:51:25 INFO gcc-12 (GCC) 12.4.0
2024/07/11 20:51:25 WARN + g++-12 --version
2024/07/11 20:51:25 WARN + grep 12.4.0
2024/07/11 20:51:25 INFO g++-12 (GCC) 12.4.0
2024/07/11 20:51:25 WARN + :
2024/07/11 20:51:25 WARN + gcc-12 -c empty.c
2024/07/11 20:51:25 WARN + :
2024/07/11 20:51:25 WARN + g++-12 -c empty.cpp
2024/07/11 20:51:25 WARN + exit 0
2024/07/11 20:51:25 INFO running step "hello world c"
2024/07/11 20:51:25 WARN + '[' -d /home/build ]
2024/07/11 20:51:25 WARN + cd /home/build
2024/07/11 20:51:25 WARN + cat
2024/07/11 20:51:25 WARN + gcc-12 -o hello-c hello.c
2024/07/11 20:51:25 WARN /usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lgcc_s: No such file or directory
2024/07/11 20:51:25 WARN collect2: error: ld returned 1 exit status
2024/07/11 20:51:25 INFO ERROR: failed to test package. the test environment has been preserved:
2024/07/11 20:51:25 INFO   workspace dir: /tmp/melange-workspace-249394094
2024/07/11 20:51:25 INFO   guest dir: /tmp/melange-guest-1318284965
2024/07/11 20:51:25 ERRO failed to build package: unable to run pipeline: unable to run pipeline: exit status 1
make: *** [Makefile:133: test/gcc-12] Error 1
```

It reproduces in a wolfi-base env after installing glibc-dev and gcc-12.
It is "fixed" by adding gcc-12-default


```
665048342e8f:/# apk add gcc-12
fetch https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz
(1/10) Installing libgcc (13.3.0-r0)
(2/10) Installing libstdc++ (13.3.0-r0)
(3/10) Installing binutils (2.42-r2)
(4/10) Installing gmp (6.3.0-r2)
(5/10) Installing isl (0.26-r4)
(6/10) Installing libstdc++-12-dev (12.4.0-r1)
(7/10) Installing mpfr (4.2.1-r4)
(8/10) Installing mpc (1.3.1-r4)
(9/10) Installing posix-cc-wrappers (1-r3)
(10/10) Installing gcc-12 (12.4.0-r1)
OK: 309 MiB in 24 packages

665048342e8f:/# apk add glibc-dev
(1/5) Installing libxcrypt-dev (4.4.36-r7)
(2/5) Installing linux-headers (6.6.29-r1)
(3/5) Installing nss-db (2.39-r7)
(4/5) Installing nss-hesiod (2.39-r7)
(5/5) Installing glibc-dev (2.39-r7)
OK: 329 MiB in 29 packages

665048342e8f:/# cat hello.c 
#include <stdio.h>
int main(int argc, char* argv[]) {
  printf("hello\n");
  return 0;
}

665048342e8f:/# gcc-12 -o hello hello.c
/usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lgcc_s: No such file or directory
collect2: error: ld returned 1 exit status

665048342e8f:/# apk add gcc-12-default
(1/1) Installing gcc-12-default (12.4.0-r1)
OK: 329 MiB in 30 packages
665048342e8f:/# gcc-12 -o hello hello.c
665048342e8f:/# ./hello
hello
```

**Comment by xnox** [comment]
@smoser

Our gcc-X package looks a bit broken to me

```
./usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/libstdc++.so
./usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/libssp.so
./usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/libquadmath.so
./usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/libgomp.so
./usr/lib/gcc/x86_64-pc-linux-gnu/12.4.0/libitm.so
./usr/lib/gcc/x86_64-pc-linux-gnu/lib64/libgcc_s.so
```

The libgcc_s.so should be in the versioned path, not in lib64 path, like all the other toolchain specific link-time library locations.

**Comment by xnox** [comment]
oh fun:

```
$ cat /usr/lib/gcc/x86_64-linux-gnu/13/libgcc_s.so
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library.  */
GROUP ( libgcc_s.so.1 -lgcc )
```

**Comment by xnox** [comment]
@smoser please review https://github.com/wolfi-dev/os/pull/23788/commits/cdb4b2951e2988547c566796827902e8ea7a1192 as that resolves correct location of version specific gcc-12's libgcc_s.so linker script.

Note that at runtime public libgcc is used.

**Review by smoser — APPROVED** [review]
Thanks for digging

**Comment by smoser** [comment]
Curious, @xnox  do you know why installation of the -default package fixed the problem?

**Comment by xnox** [comment]
> Curious, @xnox do you know why installation of the -default package fixed the problem?

See https://github.com/wolfi-dev/os/commit/cdb4b2951e2988547c566796827902e8ea7a1192#commitcomment-144181079

**Pull request merged**
