### PR TITLE
Bump ICU to 74.1.

### PR DESCRIPTION
**Pull request by dlorenc**
We had this using release-monitor instead of github which caused us to miss this release. Fix release-monitor as well.

### CODE REVIEW

**Comment by dlorenc** [comment]
Ref: https://github.com/wolfi-dev/os/pull/9822

**Comment by rawlingsj** [comment]
@dlorenc rather than push to your branch I've taken your commit and created this PR from https://github.com/wolfi-dev/os/pull/10079

**Comment by rawlingsj** [comment]
I'm not sure if I've bumped too many so didn't want to mess with your branch.

**Comment by rawlingsj** [comment]
I've moved this commit over to https://github.com/wolfi-dev/os/pull/10079 so I could push to the branch freely.  Let's close this PR and will focus on getting the other one merged.

**Pull request closed without merging**
