### PR TITLE
Make ruby version streams provide ruby

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
This gives us a "ruby" virtual that allows wolfictl to properly construct a graph and make ruby-3.2 and ruby-3.3 conflict with each other more explicitly to help the apko solver when it struggles.

### CODE REVIEW

**Comment by rawlingsj** [comment]
I know this is still in draft, but just in case I noticed there's not an epoch bump on these packages

**Review by dakaneye — DISMISSED** [review]
👍 LGTM

**Comment by smoser** [comment]
This seems "right" :+1: .
I'm not using the review due to needing epoch bump as James said.

**Comment by jonjohnsonjr** [comment]
Bumped epochs and un-drafted.

**Review by smoser — APPROVED** [review]

**Pull request merged**
