### PR TITLE
Add python versioned httpcore and hatch-fancy-pypi-readme

### PR DESCRIPTION
**Pull request by srishtih**
Adds hatch-fancy-pypi-readme with -supported and -bin subpackages needed as build time tools for httpcore

### CODE REVIEW

**Review by pnasrat — DISMISSED** [review]
Drop the supported subpackages

**Comment by srishtih** [comment]
I think its needed to build the httpcore package

**Comment by pnasrat** [comment]
We use the following pipeline so build dep shouldn't matter unless it is a
build backend

pipelines/py/pip-build-install.yaml

I believe it should just work if you list as runtime dep

Pris

**Comment by pnasrat** [comment]
If it's an actual build dep then LGTM

**Comment by srishtih** [comment]
It is an actual build time dependency for bth httpx and httpcore, the builds fail without it.

**Review by mamccorm — APPROVED** [review]

**Review by EyeCantCU — APPROVED** [review]

**Pull request merged**
