### PR TITLE
openmpi: new package and deps

### PR DESCRIPTION
**Pull request by pnasrat**
Open Source implementation of the Message Passing Interface (MPI) specification.

Signed-off-by: Pris Nasrat <pris.nasrat@chainguard.dev>

### CODE REVIEW

**Review by jamonation — COMMENTED** [review]
Any way to add a test to each of these? Would compiling a small program that uses each library be enough to validate things at the package level?

**Comment by pnasrat** [comment]
@jamonation I'll work on that for a start I'm adding openmpi tests and then I'll work backwards. Converting to draft while I do that

**Comment by pnasrat** [comment]
build failing 

```
2024/08/16 16:10:56 INFO /home/build/melange-out/openmpi/usr/lib/libmpi_usempi_ignore_tkr.la
2024/08/16 16:10:56 INFO /home/build/melange-out/openmpi/usr/lib/libmpi_mpifh.la
2024/08/16 16:10:56 INFO /home/build/melange-out/openmpi/usr/lib/libmpi.la
2024/08/16 16:10:56 INFO /home/build/melange-out/openmpi/usr/lib/openmpi/libompi_dbg_msgq.la
2024/08/16 16:10:56 INFO /home/build/melange-out/openmpi/usr/lib/libopen-pal.la
2024/08/16 16:10:56 ERRO ERROR: failed to build package. the build environment has been preserved:
2024/08/16 16:10:56 INFO   workspace dir: /tmp/melange-workspace-949572107
2024/08/16 16:10:56 INFO   guest dir: /tmp/melange-guest-2940369335
2024/08/16 16:10:56 ERRO failed to build package: unable to run package openmpi pipeline: unable to run pipeline: exit status 1
make[1]: *** [Makefile:111: packages/x86_64/openmpi-5.0.5-r0.apk] Error 1
make[1]: Leaving directory '/home/user/src/packages/wolfi-os'
make: *** [Makefile:101: package/openmpi] Error 2
```

**Comment by pnasrat** [comment]
test fails going to remove doc subpackage

```
2024/08/16 17:14:44 WARN --------------------------------------------------------------------------
2024/08/16 17:14:44 WARN Sorry!  You were supposed to get help about:
2024/08/16 17:14:44 WARN     no-compiler-found
2024/08/16 17:14:44 WARN from the file:
2024/08/16 17:14:44 WARN     /usr/share/openmpi/help-opal-wrapper.txt: No such file or directory
2024/08/16 17:14:44 WARN But I couldn't find that topic in the file.  Sorry!
2024/08/16 17:14:44 WARN --------------------------------------------------------------------------
```

**Comment by pnasrat** [comment]
```
2024/08/16 17:28:02 WARN --------------------------------------------------------------------------
2024/08/16 17:28:02 WARN The Open MPI wrapper compiler was unable to find the specified compiler
2024/08/16 17:28:02 WARN aarch64-unknown-linux-gnu-gfortran in your PATH.
2024/08/16 17:28:02 WARN
2024/08/16 17:28:02 WARN Note that this compiler was either specified at configure time or in
2024/08/16 17:28:02 WARN one of several possible environment variables.
2024/08/16 17:28:02 WARN --------------------------------------------------------------------------
```

**Pull request closed without merging**
