### PR TITLE
Fix/python missing deps

### PR DESCRIPTION
**Pull request by smoser**
this fixes some packages that used /usr/bin/python3 in their build, but did not directly depend on anything that would provide /usr/bin/python3.

Some changes to the python base packages meant that they would fail to build.

### CODE REVIEW

**Comment by smoser** [comment]
> [drop py3-urllib3-1.yaml - this is not used anywhere](https://github.com/wolfi-dev/os/pull/23381/commits/65de202ebbba63dd8a6fe9d14bc60e844b314421)

I'm sort of sure that statement is true.

**Review by rawlingsj — CHANGES_REQUESTED** [review]
A few of the packages changed in this PR are missing an epoch bump

**Comment by smoser** [comment]
This is replaced by much less invasive https://github.com/wolfi-dev/os/pull/23627 .

**Comment by rawlingsj** [comment]
> This is replaced by much less invasive https://github.com/wolfi-dev/os/pull/23627 .

sounds good, going to close this for now then, we can reopen if still needed

**Pull request closed without merging**
