### PR TITLE
use strip to shrink the size of it

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

According to the @kaniini recommendations [here](https://github.com/wolfi-dev/os/pull/116#discussion_r1028378901)

### CODE REVIEW

**Comment by kaniini** [comment]
`epoch` should be bumped so that the package gets rebuilt.

**Comment by imjasonh** [comment]
I have to admit, I don't entirely understand what `strip` does.

What does it strip from the binary, and how much smaller is it as a result?

Is there an equivalent `go build` flag we should be passing instead?

**Comment by developer-guy** [comment]
PTAL @kaniini

**Comment by tuananh** [comment]
> I have to admit, I don't entirely understand what `strip` does.
> 
> What does it strip from the binary, and how much smaller is it as a result?
> 
> Is there an equivalent `go build` flag we should be passing instead?

i think it's equivalent to `go install -ldflags '-s'`

**Comment by imjasonh** [comment]
> i think it's equivalent to `go build -ldflags '-s'`

In that case, should we just `go build` with those flags? Maybe we need a `go-build` built-in pipeline that sets that flag, and any other common flags we expect to find.

**Comment by tuananh** [comment]
> > i think it's equivalent to `go build -ldflags '-s'`
> 
> In that case, should we just `go build` with those flags? Maybe we need a `go-build` built-in pipeline that sets that flag, and any other common flags we expect to find.

@puerco is already working on that here https://github.com/chainguard-dev/melange/pull/180

but no default ldflags is set.

**Review by kaniini — DISMISSED** [review]

**Review by kaniini — APPROVED** [review]

**Pull request merged**
