### PR TITLE
add fuse3 and deps, cairo, eudev, gobject-introspection, kmod, pixman…

### PR DESCRIPTION
**Pull request by rawlingsj**
… and xcb-util

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

### CODE REVIEW

**Comment by rawlingsj** [comment]
I'm not 100% if these are needed or useful in wolfi + some feel a bit complex so may need some discussion.  I was going to split out but as I don't know enough, I figured push as a draft PR to get visibility from folks next week and anyone considering the same packages

**Comment by tuananh** [comment]
@rawlingsj should we have testing/community repo like alpine? new packages like this could be move to testing instead?

**Comment by rawlingsj** [comment]
I'm not sure these are related to testing as they seem to be required for core dependencies.  But we have talked in the past about having different repos to core.  Maybe start a github discussion or bring it up at the wolfi office hours?

**Review by kaniini — APPROVED** [review]

**Comment by kaniini** [comment]
> @rawlingsj should we have testing/community repo like alpine? new packages like this could be move to testing instead?

I don't want to do this for a number of reasons.  In Alpine, the purpose of `testing` is commonly confused and packages just wind up rotting there.  I also don't see the point in `community`, as it creates problems, and we do not have the same support model as Alpine.

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
