### PR TITLE
Fix curl rustls

### PR DESCRIPTION
**Pull request by xnox**
Related: https://github.com/wolfi-dev/os/pull/15642 https://github.com/wolfi-dev/os/pull/12950
Closes: https://github.com/wolfi-dev/os/pull/12398

### CODE REVIEW

**Comment by xnox** [comment]
bah

**Comment by xnox** [comment]
@ajayk this finally fixes rusttls / rustls-ffi / curl-rustls updates.

**Comment by rawlingsj** [comment]
curl-rustls.yaml will need an epoch bump for the patch to to applied.

**Comment by xnox** [comment]
@rawlingsj can we have a git commit hook that does `wolfictl bump` ?!

**Review by rawlingsj — APPROVED** [review]

**Pull request merged**
