### PR TITLE
package: perl-lwp-protocol-https

### PR DESCRIPTION
**Pull request by mesaglio**

### CODE REVIEW

**Comment by mesaglio** [comment]
@EyeCantCU can you help me with this pr?

**Comment by EyeCantCU** [comment]
For sure!

**Comment by mesaglio** [comment]
[This error](https://github.com/wolfi-dev/os/actions/runs/11941385197/job/34479330735?pr=34766) is related with me pr?

**Comment by EyeCantCU** [comment]
@mesaglio looks like a remnant of when we used GH builders, completely unrelated. Updated the branch, that should fix it

**Review by EyeCantCU — APPROVED** [review]

**Pull request merged**
