### PR TITLE
Add libjpeg-turbo

### PR DESCRIPTION
**Pull request by dlorenc**
This is required for nginx.

Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>

### CODE REVIEW

**Comment by dlorenc** [comment]
Requires https://github.com/wolfi-dev/os/pull/326

**Comment by tuananh** [comment]
Are they the same ? https://github.com/wolfi-dev/os/blob/main/libjpeg.yaml

**Comment by dlorenc** [comment]
> Are they the same ? https://github.com/wolfi-dev/os/blob/main/libjpeg.yaml

oooh yeah! it looks like our libjpeg is libjpeg-turbo. I wonder if we should add a "provides" to it? Some packages I was porting require libjpeg-turbo explicity: https://git.alpinelinux.org/aports/tree/main/libwebp/APKBUILD?h=3.3-stable#n12

**Comment by dlorenc** [comment]
Closing this for now, but opening an issue to sort it out: https://github.com/wolfi-dev/os/issues/334

**Pull request closed without merging**
