### PR TITLE
Add e2fsprogs and keyutils pkg

### PR DESCRIPTION
**Pull request by tuananh**
these 2 are needed in order to build krb5 (keberos) and later on php82

### CODE REVIEW

**Comment by rawlingsj** [comment]
@tuananh totally happy to add these, just so you know I've got a bunch of PRs ready to come in for krb5 and all the other deps.  I got the last dependency built just now.  Will do a diff of these two and mine too.

**Comment by tuananh** [comment]
> @tuananh totally happy to add these, just so you know I've got a bunch of PRs ready to come in for krb5 and all the other deps.  I got the last dependency built just now.  Will do a diff of these two and mine too.

I want to pack them all together but im stuck with krb5 at the moment

Autoconf fails at the step checking ss package

**Comment by rawlingsj** [comment]
The related deps I'm pushing this morning are e2fsprogs, unixodbc, cjson, libwebsockets, mosquitto, groff, db, openldap, libverto, krb5, then onto bind-tools.  Also got glib, xcb-utils, and some other related to fuse.

**Comment by tuananh** [comment]
Is there a list of what everyone is working on atm so that we wont step onto eachother foot?

**Comment by tuananh** [comment]
Also feel free to close this since yours is more completed

**Comment by rawlingsj** [comment]
> Is there a list of what everyone is working on atm so that we wont step onto eachother foot?

I agree. Maybe we can add a task list to an issue or a GitHub discussion.  I've had the same thoughts.

**Comment by rawlingsj** [comment]
Ok cool - up to you, we can try and merge mine with yours here via comments or just close.  I don't mind really just sensitive to you having done work on this too.

As an example this is my e2fsprogs https://gist.github.com/rawlingsj/4734aae5dc2dcff6055f4fd0a6c73daa
and keyutils https://gist.github.com/rawlingsj/2bc48b7805ef41e14e0662a82941dfe4

I should be able to push everything in an hour or so.

**Comment by tuananh** [comment]
Its no problem, really

**Comment by rawlingsj** [comment]
@tuananh BTW this is the completed krb5 package https://gist.github.com/rawlingsj/7e9159e6f7d5ba8d32e995258d6b6f5c

I've just noticed a couple of symlink errors in one of my dependencies so need to fix that + test before creating the PRs.  So it's close!  Wanted to share it with you early though.

**Comment by tuananh** [comment]
Nice. Lemme diff to see where i got it wrong :))

**Comment by rawlingsj** [comment]
Cool :)  I am also just checking https://gist.github.com/rawlingsj/7e9159e6f7d5ba8d32e995258d6b6f5c#file-krb5-yaml-L69-L73 and the generated depends compared with alpine too, as want to keep them the same so packages that use krb5 "should just work"

**Pull request closed without merging**
