### PR TITLE
Mitigate the x/net and x/text GHSA's in gomplate and dex.

### PR DESCRIPTION
**Pull request by dlorenc**
This gives us a clean dex image! Both of these bumps were done upstream but they haven't been released yet.

### CODE REVIEW

**Comment by rawlingsj** [comment]
This is probably a fine way to do this.  FWIW In the past I have made local changes to a `go.mod` file and created a `cve.patch` file using `git diff > cve.patch` then added that to the melange patch list as normal.  

@dlorenc just in case you prefer that approach, I don't have a preference either way but figured I'd mention it just in case.

**Comment by rawlingsj** [comment]
Shall we go with the current approach in this PR for now?

**Comment by dlorenc** [comment]
> This is probably a fine way to do this. FWIW In the past I have made local changes to a `go.mod` file and created a `cve.patch` file using `git diff > cve.patch` then added that to the melange patch list as normal.
> 
> @dlorenc just in case you prefer that approach, I don't have a preference either way but figured I'd mention it just in case.

I stole this pattern from `git-lfs` here: https://github.com/wolfi-dev/os/blob/main/git-lfs.yaml#L35 - I don't really have a strong preference either way either.

**Review by rawlingsj — APPROVED** [review]

**Comment by rawlingsj** [comment]
Ah cool - yeah lets' go with that

**Pull request merged**
