### PR TITLE
Fix lua-rest-ipmatcher package.

### PR DESCRIPTION
**Pull request by dlorenc**
Fixes:

Related:

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @tcnghia - this package was empty, the destdir stuff doesn't work here.

**Review by tcnghia — APPROVED** [review]

**Comment by tcnghia** [comment]
> cc @tcnghia - this package was empty, the destdir stuff doesn't work here.

Thanks!!!

**Comment by luhring** [comment]
> this package was empty

Just curious — literally? Is this something melange should be checking and failing for?

**Comment by dlorenc** [comment]
> > this package was empty
> 
> Just curious — literally? Is this something melange should be checking and failing for?

Yep! there was nothing in there but directories and an SBOM.

**Pull request merged**
