### PR TITLE
revert: icu 76.1 package update as contains ABI breakage, bumps dependants that have already been built with new ABI

### PR DESCRIPTION
**Pull request by rawlingsj**
see https://github.com/wolfi-dev/os/pull/35274

package update check is expected to fail as we are rolling back an update.

### CODE REVIEW

**Review by xnox — DISMISSED** [review]

**Comment by xnox** [comment]
Also likely want to withdraw 76.1 APKs

**Comment by rawlingsj** [comment]
> Also likely want to withdraw 76.1 APKs

yeah lemme push another commit to this PR

**Review by maxgio92 — DISMISSED** [review]

**Review by sil2100 — COMMENTED** [review]
LGTM

**Review by xnox — DISMISSED** [review]

**Comment by maxgio92** [comment]
Tensorflow build was complaining during Bazel build because the Python version in the hermetic environment was defaulted to the latest 3.13 while Tensworflow's Bazel workspace doesn't support a requirements_lock.txt for 3.13.

**Comment by xnox** [comment]
The builds are good; i cannot tell if they are out of order or not; we may need to bump/rebuild a few more things; but I would rather land this sooner than later. As a lot more things are currently broken; or can get more broken as things are landing.

**Review by xnox — APPROVED** [review]

**Pull request merged**
