### PR TITLE
ruby 3.4: gems batch 3

### PR DESCRIPTION
**Pull request by justinvreeland**
Copy the 3.3 gems, update the version, cleanup uneeded patches if present. Add rsppec a common build tool to avoid build time install via bundler.

### CODE REVIEW

**Comment by justinvreeland** [comment]
Diff from cp and sed. https://github.com/justinvreeland/wolfi/commit/6426151534dec524fd0ae5284f992ec7e9393b54

**Comment by justinvreeland** [comment]
Looking at the test failures. I suspect it missed packages from the latest merge like 2 was.

**Review by smoser — APPROVED** [review]

**Comment by justinvreeland** [comment]
> Looking at the test failures. I suspect it missed packages from the latest merge like 2 was.

```
2024/12/12 15:31:20 ERRO failed to test package: unable to build guest: unable to generate image: installing apk packages: error getting package dependencies: solving "ruby3.4-ffi-compiler" constraint: could not find package either named ruby3.4-ffi or that provides ruby3.4-ffi for ruby3.4-ffi-compiler
```

Just need to wait a bit for the repos to sync, ruby3.4-ffi was in batch 2.

**Review by smoser — APPROVED** [review]
Just checking your work, looks good.
the tldr - no changes other than expected. +1. thanks.

```
$ for p in $(changed-files HEAD^); do n=ruby3.3-${p#ruby3.4-}; diff -u $n $p; done | grep -- "^[-+]"
--- ruby3.3-aws-sdk-core.yaml	2024-12-09 14:30:36.520926504 -0500
+++ ruby3.4-aws-sdk-core.yaml	2024-12-17 15:14:04.897058978 -0500
-  name: ruby3.3-aws-sdk-core
+  name: ruby3.4-aws-sdk-core
--- ruby3.3-ffi-compiler.yaml	2024-12-09 14:30:36.523926465 -0500
+++ ruby3.4-ffi-compiler.yaml	2024-12-17 15:14:04.897058978 -0500
-  name: ruby3.3-ffi-compiler
+  name: ruby3.4-ffi-compiler
--- ruby3.3-i18n.yaml	2024-12-09 14:30:36.524926451 -0500
+++ ruby3.4-i18n.yaml	2024-12-17 15:14:04.897058978 -0500
-  name: ruby3.3-i18n
+  name: ruby3.4-i18n
--- ruby3.3-redis.yaml	2024-12-09 14:30:36.529926386 -0500
+++ ruby3.4-redis.yaml	2024-12-17 15:14:04.897058978 -0500
-  name: ruby3.3-redis
+  name: ruby3.4-redis
--- ruby3.3-rest-client.yaml	2024-12-09 14:30:36.529926386 -0500
+++ ruby3.4-rest-client.yaml	2024-12-17 15:14:04.898058966 -0500
-  name: ruby3.3-rest-client
+  name: ruby3.4-rest-client
diff: ruby3.3-rspec.yaml: No such file or directory
--- ruby3.3-sidekiq.yaml	2024-12-09 14:30:36.530926373 -0500
+++ ruby3.4-sidekiq.yaml	2024-12-17 15:14:04.898058966 -0500
-  name: ruby3.3-sidekiq
+  name: ruby3.4-sidekiq
--- ruby3.3-sinatra.yaml	2024-12-09 14:30:36.530926373 -0500
+++ ruby3.4-sinatra.yaml	2024-12-17 15:14:04.898058966 -0500
-  name: ruby3.3-sinatra
+  name: ruby3.4-sinatra
--- ruby3.3-systemd-journal.yaml	2024-12-09 14:30:36.530926373 -0500
+++ ruby3.4-systemd-journal.yaml	2024-12-17 15:14:04.898058966 -0500
-  name: ruby3.3-systemd-journal
+  name: ruby3.4-systemd-journal
--- ruby3.3-tzinfo.yaml	2024-12-09 14:30:36.531926360 -0500
+++ ruby3.4-tzinfo.yaml	2024-12-17 15:14:04.898058966 -0500
-  name: ruby3.3-tzinfo
+  name: ruby3.4-tzinfo
```

**Pull request merged**
