### PR TITLE
GHSA-45x7-px36-x8w8 : fix CVE for Wolfi package caddy

### PR DESCRIPTION
**Pull request by hectorj2f**
Fix for GHSA-45x7-px36-x8w8 using wolfi-bump.

### CODE REVIEW

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
Looks like the bump got dropped

**Review by dlorenc — CHANGES_REQUESTED** [review]
Need to add the go/bump pipeline somewhere

**Comment by hectorj2f** [comment]
Great! It seems we found a bug. Fixing it 🔨 !

**Comment by hectorj2f** [comment]
Closing this in favour of a new PR!

**Pull request closed without merging**
