### PR TITLE
fix(linux-pam): Relocate PAM configuration files from util-linux to linux-pam

### PR DESCRIPTION
**Pull request by EyeCantCU**
Fixes: This moves PAM configuration files out of util-linux and into pam-linux, properly installs the configuration files, and creates a PAM configuration file in util-linux for sulogin

### CODE REVIEW

**Review by imjasonh — COMMENTED** [review]
Is there a package test we could add for this to give us more confidence this is the correct way to install this?

Ideally something that would have failed prior to this change, but passes now?

**Comment by EyeCantCU** [comment]
> Is there a package test we could add for this to give us more confidence this is the correct way to install this?
> 
> Ideally something that would have failed prior to this change, but passes now?

Yup :). Should be as easy as verifying `su` works as currently it fails. I will write one up

**Comment by EyeCantCU** [comment]
A test has been added :)

**Review by imjasonh — APPROVED** [review]
Thanks!

**Pull request merged**
