### PR TITLE
Python version stream

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
Marked as draft for now to see what issues CI catches, there's more changes to add to this PR.

**Comment by tuananh** [comment]
@rawlingsj how do you generate name of all packages depends on `python3`? do we have a tool to generate such dependency graph?

**Comment by rawlingsj** [comment]
> how do you generate name of all packages depends on python3? do we have a tool to generate such dependency graph?

We have the start of it, wolfictl does some functionality of a bump, we need to look at tying in [dag](https://github.com/wolfi-dev/dag) to know downstream packages that we need to bump in situations like this.  For now it was manual but the plan is for it to be automated soon.

**Comment by rawlingsj** [comment]
Closing this PR as we went for a simpler option https://github.com/wolfi-dev/os/pull/549

**Pull request closed without merging**
