### PR TITLE
cilium: Add support for cilium v1.16.x

### PR DESCRIPTION
**Pull request by sayboras**
This commit is to add the support for cilium v1.16 (will be released soon). The current version v1.16.0-rc.2 is used for testing purpose.

Fixes: NA

Related: NA

#### For new version streams

- [x] The upstream project actually supports multiple concurrent versions.
- [x] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [x] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [x] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Comment by ajayk** [comment]
This would be handled by our automation when the cilium
Releases 1.16 
we don't support rc versions as it has created unnecessary maintenance burden , we just have few packages with exceptions

**Comment by sayboras** [comment]
> This would be handled by our automation when the cilium Releases 1.16 we don't support rc versions

Makes sense, I will swap the version once v1.16 is release. Mark this as draft now.

**Comment by mamccorm** [comment]
Thanks for the contribution @sayboras. We don't build pre-release package versions, but whenever officially released, our automation will pick-up on this and create the new version

**Comment by sayboras** [comment]
> whenever officially released, our automation will pick-up on this and create the new version

Nice, I don't know how it works, but let's see how it's going. Cilium v1.16 is released today.

https://github.com/cilium/cilium/releases/tag/v1.16.0

**Pull request closed without merging**
