### PR TITLE
pull-request-template: improve checklists for package splits, moves, removals

### PR DESCRIPTION
**Pull request by xnox**
Add new checklist items for package splits and renames:

- add checklist item for package splits/renames which are part of base images
- add checklist item for removed non-stream packages

Related:
https://github.com/wolfi-dev/os/pull/14133
https://github.com/wolfi-dev/os/pull/14307
https://github.com/wolfi-dev/os/pull/14313
https://github.com/wolfi-dev/os/pull/14317

https://github.com/wolfi-dev/os/pull/549
https://github.com/wolfi-dev/os/pull/14691

CC: @smoser @ajayk @jonjohnsonjr

### CODE REVIEW

**Review by smoser — COMMENTED** [review]
It would be best if we could have c-i assert these check-listed items were achieved rather than expecting humans to do so. 

any chance that is possible?

**Comment by xnox** [comment]
> It would be best if we could have c-i assert these check-listed items were achieved rather than expecting humans to do so.

.... Yes, I don't know if that belongs here, or in chainguard-images/images repo, or in actions repo, or to the tools team. I will ask.

**Comment by xnox** [comment]
> It would be best if we could have c-i assert these check-listed items were achieved rather than expecting humans to do so.
> 
> any chance that is possible?

@smoser I've now completed this for verification of libxcrypt transition attempt number two.

It is difficult.

1) build new packages in wolfi-dev/os checkout
2) transfer packages from wolfi-dev/os to wolfi-tools/tools
3) build sdk package in wolfi-dev/tools
4) create local registry (for example by using `make k3d` from chainguard-images/images)
5) export local registry with sdk image name into the environment
6) trigger sdk image build in wolfi-dev/tools/images/sdk (aka terraform apply)
7) go back to wolfi-dev/os and change sdk image url & hashes to the local registry
8) execute test-builds and testing

However I can propose quick-checks to be added to the sdk image for verification of "all packages are up to date". As non-blocking for now.

**Review by smoser — APPROVED** [review]
I'm not opposed to the format change, somehwere along the line hopefully we catch stuff in test.

**Pull request merged**
