### PR TITLE
dotnet-8: use offline build

### PR DESCRIPTION
**Pull request by ader1990**
Dotnet-8 tag 8.0.10 or older cannot be built anymore, as Microsoft decided to retire the following repositories:

  * https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL.Selfhost/nuget/v3/index.json
  * https://pkgs.dev.azure.com/ms/BuildXL/_packaging/BuildXL/nuget/v3/index.json

The repositories were replaced with:

  * https://pkgs.dev.azure.com/mseng/PipelineTools/_packaging/BuildXL.External.Dependencies/nuget/v3/index.json

The problem is that the tagged releases of dotnet <= 8.0.10 will never be able to build anymore, as tags cannot be replaced.

The fix has landed to https://github.com/dotnet/msbuild/pull/10838, and the following tagged releases should be buildable again.

See: https://github.com/microsoft/BuildXL/issues/1343

But, if we leverage the offline build, after the prep.sh has been run, there is no required connection to the inexistent repositories, thus the build will work for the old tags too.

Fixes:

Related:

#### For new package PRs only

- [ ] This PR is marked as fixing a pre-existing package request bug
  - [ ] Alternatively, the PR is marked as related to a pre-existing package request bug, such as a dependency
- [ ] REQUIRED - The package is available under an OSI-approved or FSF-approved license
- [ ] REQUIRED - The version of the package is still receiving security updates
- [ ] This PR links to the upstream project's support policy (e.g. `endoflife.date`)

#### For new version streams

- [ ] The upstream project actually supports multiple concurrent versions.
- [ ] Any subpackages include the version string in their package name (e.g. `name: ${{package.name}}-compat`)
- [ ] The package (and subpackages) `provides:` logical unversioned forms of the package (e.g. `nodejs`, `nodejs-lts`)
- [ ] If non-streamed package names no longer built, open PR to withdraw them (see [WITHDRAWING PACKAGES](https://github.com/wolfi-dev/os/blob/main/WITHDRAWING_PACKAGES.md))

#### For package updates (renames) in the base images

When updating packages part of base images (i.e. cgr.dev/chainguard/wolfi-base or ghcr.io/wolfi-dev/sdk)
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk images successfully build
- [ ] REQUIRED cgr.dev/chainguard/wolfi-base and ghcr.io/wolfi-dev/sdk contain no obsolete (no longer built) packages
- [ ] Upon launch, does `apk upgrade --latest` successfully upgrades packages or performs no actions

#### For security-related PRs

- [ ] The security fix is recorded in the [advisories](https://github.com/wolfi-dev/advisories) repo

#### For version bump PRs

- [ ] The `epoch` field is reset to 0

#### For PRs that add patches

- [ ] Patch source is documented

### CODE REVIEW

**Review by xnox — CHANGES_REQUESTED** [review]
Hi,

Unlike other distributions we do not automatically upgrade the package version number upon changes in git. To actually trigger post-submit build and upgrade the package one needs to bump epoch; or if new upstream version is increased reset epoch back to zero. (this is equivalent to creating a new changelog entry in debian/changelog to increase the .deb build number, or increasing Release field in rpm spec file)

One can manually edit "epoch: 0" to "epoch: 1" or use `wolfictl bump dotnet-8.yaml` (one can install wolfictl with `go install github.com/wolfi-dev/wolfictl@latest` or it is available as preinstalled in the sdk container, one can enter it with docker using `make dev-container`)

The GHA pre-submit checks attempt re-builds for any diff, but not elastic builds, nor post submit (post merge).

Thanks.

**Comment by xnox** [comment]
> > Hi,
> > Unlike other distributions we do not automatically upgrade the package version number upon changes in git. To actually trigger post-submit build and upgrade the package one needs to bump epoch; or if new upstream version is increased reset epoch back to zero. (this is equivalent to creating a new changelog entry in debian/changelog to increase the .deb build number, or increasing Release field in rpm spec file)
> > One can manually edit "epoch: 0" to "epoch: 1" or use `wolfictl bump dotnet-8.yaml` (one can install wolfictl with `go install github.com/wolfi-dev/wolfictl@latest` or it is available as preinstalled in the sdk container, one can enter it with docker using `make dev-container`)
> > The GHA pre-submit checks attempt re-builds for any diff, but not elastic builds, nor post submit (post merge).
> > Thanks.
> 
> Hello,
> 
> In theory, this PR will not be changing anything in the outcome of the package build, it just fixes the build. If one tries now to build the package, it will fail, as the required build time download links won't work anymore.
> 
> Do you suggest to bump the epoch even in this case?
> 
> Thanks.

Yes please. We bump epoch for any fixes to build failures, to ensure a rebuild is done with new changes with a full set of post-submit CI and is known to work.

As otherwise we loose an easy way to track which packaging / git commit was used to build -r0 (it is encoded inside the .apk but hard to extract).

At the moment, we don't bump epoch for `test:` dictionary only changes, as those are executed/exercised across the whole archive on every push.

**Comment by xnox** [comment]
GHA rebuilds are now green.

Epoch bump is needed to pacify & merging this:
https://github.com/wolfi-dev/os/pull/33140/checks?check_run_id=32473187305 
https://github.com/wolfi-dev/os/pull/33140/checks?check_run_id=32473214986

**Review by xnox — APPROVED** [review]

**Comment by xnox** [comment]
@ader1990 bumping epoch for you; but it means i will have to get external reviewer, as i am prohibited from self-merging code now as the last pusher.

**Comment by ader1990** [comment]
> @ader1990 bumping epoch for you; but it means i will have to get external reviewer, as i am prohibited from self-merging code now as the last pusher.

I can force-push it, if that is okay?

**Comment by xnox** [comment]
> > @ader1990 bumping epoch for you; but it means i will have to get external reviewer, as i am prohibited from self-merging code now as the last pusher.
> 
> I can force-push it, if that is okay?

yes please.

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
