### PR TITLE
add helm

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

### CODE REVIEW

**Comment by developer-guy** [comment]
PTAL @mattfarina @hickeyma

**Review by amouat — DISMISSED** [review]

**Review by dlorenc — DISMISSED** [review]

**Comment by tuananh** [comment]
```
2023/01/02 18:31:50 melange (helm/x86_64): fatal: not a git repository (or any of the parent directories): .git
2023/01/02 18:31:50 melange (helm/x86_64): fatal: not a git repository (or any of the parent directories): .git
```

these commands in makefile will fail. we need to find a way to do about this as it's used in lots of projects. maybe instead of fetching, do proper git fetch ?

```
GIT_COMMIT = $(shell git rev-parse HEAD)
GIT_SHA    = $(shell git rev-parse --short HEAD)
GIT_TAG    = $(shell git describe --tags --abbrev=0 --exact-match 2>/dev/null)
GIT_DIRTY  = $(shell test -n "`git status --porcelain`" && echo "dirty" || echo "clean")
```

**Comment by tuananh** [comment]
i propose maybe we can do a shallow clone to speed up the CI for large project

```yaml
package:
  name: helm
  version: 3.10.3
  epoch: 0
  description: The Kubernetes Package Manager
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - ca-certificates-bundle
environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base
      - git
pipeline:
  - runs: |
      git clone https://github.com/helm/helm --depth=1 --single-branch --branch=v${{package.version}}
      cd helm
      git checkout -b v${{package.version}}
      make build
      install -Dm755 ./bin/helm "${{targets.destdir}}/usr/bin/helm"
  - uses: strip
```

**Comment by tuananh** [comment]
Related issue in PR #426

**Comment by rawlingsj** [comment]
Does using something like this help? https://github.com/wolfi-dev/os/blob/767464a797d581d4ce76a6afc10bef5e3c09ac8a/envoy.yaml#L37-L41

It uses git and the --depth flag as mentioned above 

https://github.com/chainguard-dev/melange/blob/b60bf34fc9c91324cda0d9f9438386865ca92b28/pkg/build/pipelines/git-checkout.yaml#L30

**Comment by tuananh** [comment]
Nice. I must have missed it

**Review by rawlingsj — APPROVED** [review]

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
